/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residence;

import View.RoundedLineBorder;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Locale;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author farid
 */
public class AddWilaya extends javax.swing.JFrame {

    ConnectionDB cnx = new ConnectionDB();

    Home1 home;
    Conf conf;
    int chouceGui;
    Get_Info_DB Fill_Data = new Get_Info_DB();
    RoundedLineBorder roundedLineBorder = new RoundedLineBorder(Color.BLACK, 1, 10, true);

    public AddWilaya(Home1 objGui) {// Constructor of Home Form
        initComponents();
        this.home = objGui;
        chouceGui = 1;
    }

    public AddWilaya(Conf objGui) { // Constructor of form Configuration
        initComponents();
        this.conf = objGui;
        chouceGui = 2;
    }

    public void PrepareCreateGuiForm() {
        this.setLocationRelativeTo(this);
        ButtonGroup grp = new ButtonGroup();
        grp.add(RdiBtnWil);
        grp.add(RdiBtnDai);
        grp.add(RdiBtnCom);
        Fill_Data.Filling(CmbWilDaira, "Wilaya", "NameWilaya", 1);
        Fill_Data.Filling(CombWilCom, "Wilaya", "NameWilaya", 1);
        CombWilCom.setSelectedIndex(1);
        FillTableCommune_Combobox((String) CombWilCom.getSelectedItem(), TableCommune, null, 0);
        FillTableWilaya(TableWilaya);
        //FillingAllUnit_InTable(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RdiBtnWil = new javax.swing.JRadioButton();
        RdiBtnDai = new javax.swing.JRadioButton();
        RdiBtnCom = new javax.swing.JRadioButton();
        ContainairDetaills = new javax.swing.JPanel();
        InsidPanWilaya = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableWilaya = new javax.swing.JTable(){

            public Class getColumnClass(int column) {
                return (column == 0 || column == 1 || column == 2 ) ? Icon.class : Object.class;
            }

        };
        jLabel13 = new javax.swing.JLabel();
        WilayAr = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        WilayFr = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        NumWily = new javax.swing.JTextField();
        buttonView4 = new View.ButtonView();
        BtnUpdtSaveWilaya = new View.ButtonView();
        SearchWilayaTXT = new View.TextField();
        HintToUser = new javax.swing.JLabel();
        buttonView5 = new View.ButtonView();
        AddNewWilayaLab = new javax.swing.JLabel();
        IconClearSrchWilay = new javax.swing.JLabel();
        InsidPanDaira = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){

            public Class getColumnClass(int column) {
                return (column == 0 || column == 1 ) ? Icon.class : Object.class;
            }

        };
        jLabel7 = new javax.swing.JLabel();
        CmbWilDaira = new View.Combobox();
        jLabel8 = new javax.swing.JLabel();
        NameDaireAR = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        NameDaireFR = new javax.swing.JTextField();
        SearchWilayaTXT1 = new View.TextField();
        InsidPanCommune = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCommune = new javax.swing.JTable();
        Code_ComLab = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SearchTxtCommune = new javax.swing.JTextField();
        CombWilCom = new View.Combobox();
        LabUpdt = new javax.swing.JLabel();
        NewCommuneLab = new javax.swing.JLabel();
        NameCommuneAR = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NameCommuneFR = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        CodeCom = new javax.swing.JTextField();
        BtnSavUpdate = new View.ButtonView();
        jLabel2 = new javax.swing.JLabel();
        buttonView3 = new View.ButtonView();
        buttonView2 = new View.ButtonView();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(230, 230, 210));

        RdiBtnWil.setBackground(new java.awt.Color(230, 230, 210));
        RdiBtnWil.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RdiBtnWil.setSelected(true);
        RdiBtnWil.setText("اضافة الولاية");
        RdiBtnWil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RdiBtnWil.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        RdiBtnWil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdiBtnWilActionPerformed(evt);
            }
        });

        RdiBtnDai.setBackground(new java.awt.Color(230, 230, 210));
        RdiBtnDai.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RdiBtnDai.setText("اضافة دائرة");
        RdiBtnDai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RdiBtnDai.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        RdiBtnDai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdiBtnDaiActionPerformed(evt);
            }
        });

        RdiBtnCom.setBackground(new java.awt.Color(230, 230, 210));
        RdiBtnCom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RdiBtnCom.setText("اضافة بلدية");
        RdiBtnCom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RdiBtnCom.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        RdiBtnCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdiBtnComActionPerformed(evt);
            }
        });

        ContainairDetaills.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ContainairDetaills.setLayout(new java.awt.CardLayout());

        InsidPanWilaya.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        TableWilaya.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TableWilaya.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "حذف", "تعديل", "جديد", "Wilaya", "الولاية", "الرقــم"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableWilaya.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TableWilaya.setGridColor(new java.awt.Color(0, 0, 0));
        TableWilaya.setRowHeight(30);
        TableWilaya.setSelectionBackground(new java.awt.Color(102, 0, 102));
        TableWilaya.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                TableWilayaMouseMoved(evt);
            }
        });
        TableWilaya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableWilayaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TableWilayaMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(TableWilaya);
        if (TableWilaya.getColumnModel().getColumnCount() > 0) {
            TableWilaya.getColumnModel().getColumn(0).setMinWidth(60);
            TableWilaya.getColumnModel().getColumn(0).setPreferredWidth(60);
            TableWilaya.getColumnModel().getColumn(0).setMaxWidth(60);
            TableWilaya.getColumnModel().getColumn(1).setMinWidth(60);
            TableWilaya.getColumnModel().getColumn(1).setPreferredWidth(60);
            TableWilaya.getColumnModel().getColumn(1).setMaxWidth(60);
            TableWilaya.getColumnModel().getColumn(2).setMinWidth(0);
            TableWilaya.getColumnModel().getColumn(2).setPreferredWidth(0);
            TableWilaya.getColumnModel().getColumn(2).setMaxWidth(0);
            TableWilaya.getColumnModel().getColumn(5).setMinWidth(50);
            TableWilaya.getColumnModel().getColumn(5).setPreferredWidth(50);
            TableWilaya.getColumnModel().getColumn(5).setMaxWidth(50);
        }

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("الولاية");

        WilayAr.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        WilayAr.setForeground(new java.awt.Color(153, 153, 153));
        WilayAr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WilayAr.setText("الولاية");
        WilayAr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                WilayArFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                WilayArFocusLost(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Wilaya");

        WilayFr.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        WilayFr.setForeground(new java.awt.Color(153, 153, 153));
        WilayFr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WilayFr.setText("Wilaya");
        WilayFr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                WilayFrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                WilayFrFocusLost(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("الرقم");

        NumWily.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NumWily.setForeground(new java.awt.Color(153, 153, 153));
        NumWily.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumWily.setText("الرقم");
        NumWily.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NumWilyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NumWilyFocusLost(evt);
            }
        });

        buttonView4.setBackground(new java.awt.Color(0, 102, 102));
        buttonView4.setForeground(new java.awt.Color(255, 255, 255));
        buttonView4.setText("الغاء");
        buttonView4.setBackgroundPainted(true);
        buttonView4.setBorderPainted(false);
        buttonView4.setEntred(false);
        buttonView4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonView4.setRounded(true);
        buttonView4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonView4ActionPerformed(evt);
            }
        });

        BtnUpdtSaveWilaya.setBackground(new java.awt.Color(0, 102, 102));
        BtnUpdtSaveWilaya.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpdtSaveWilaya.setText("حفظ");
        BtnUpdtSaveWilaya.setBackgroundPainted(true);
        BtnUpdtSaveWilaya.setBorderPainted(false);
        BtnUpdtSaveWilaya.setEntred(false);
        BtnUpdtSaveWilaya.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnUpdtSaveWilaya.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnUpdtSaveWilaya.setRounded(true);
        BtnUpdtSaveWilaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdtSaveWilayaActionPerformed(evt);
            }
        });

        SearchWilayaTXT.setForeground(new java.awt.Color(204, 204, 204));
        SearchWilayaTXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SearchWilayaTXT.setText("البحث");
        SearchWilayaTXT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        SearchWilayaTXT.setLabelText("");
        SearchWilayaTXT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchWilayaTXTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchWilayaTXTFocusLost(evt);
            }
        });
        SearchWilayaTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchWilayaTXTKeyReleased(evt);
            }
        });

        HintToUser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        HintToUser.setForeground(new java.awt.Color(204, 0, 0));
        HintToUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        buttonView5.setBackground(new java.awt.Color(0, 102, 102));
        buttonView5.setForeground(new java.awt.Color(255, 255, 255));
        buttonView5.setText("خروج");
        buttonView5.setBackgroundPainted(true);
        buttonView5.setBorderPainted(false);
        buttonView5.setEntred(false);
        buttonView5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonView5.setRounded(true);
        buttonView5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonView5ActionPerformed(evt);
            }
        });

        AddNewWilayaLab.setBackground(new java.awt.Color(255, 255, 255));
        AddNewWilayaLab.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AddNewWilayaLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddNewWilayaLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residence/Image/C_Add_Mini_h.png"))); // NOI18N
        AddNewWilayaLab.setText("اضافة ولاية");
        AddNewWilayaLab.setToolTipText("اضافة ولاية جديدة");
        AddNewWilayaLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddNewWilayaLab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddNewWilayaLab.setOpaque(true);
        AddNewWilayaLab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AddNewWilayaLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddNewWilayaLabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddNewWilayaLabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddNewWilayaLabMouseExited(evt);
            }
        });

        IconClearSrchWilay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconClearSrchWilay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IconClearSrchWilay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconClearSrchWilayMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout InsidPanWilayaLayout = new javax.swing.GroupLayout(InsidPanWilaya);
        InsidPanWilaya.setLayout(InsidPanWilayaLayout);
        InsidPanWilayaLayout.setHorizontalGroup(
            InsidPanWilayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsidPanWilayaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InsidPanWilayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsidPanWilayaLayout.createSequentialGroup()
                        .addGroup(InsidPanWilayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InsidPanWilayaLayout.createSequentialGroup()
                                .addComponent(buttonView5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonView4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(148, 148, 148))
                            .addGroup(InsidPanWilayaLayout.createSequentialGroup()
                                .addGroup(InsidPanWilayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnUpdtSaveWilaya, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(InsidPanWilayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WilayAr)
                            .addComponent(WilayFr, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumWily, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(InsidPanWilayaLayout.createSequentialGroup()
                        .addComponent(AddNewWilayaLab, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198)
                        .addComponent(IconClearSrchWilay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchWilayaTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(HintToUser, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        InsidPanWilayaLayout.setVerticalGroup(
            InsidPanWilayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsidPanWilayaLayout.createSequentialGroup()
                .addGroup(InsidPanWilayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsidPanWilayaLayout.createSequentialGroup()
                        .addComponent(HintToUser, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(InsidPanWilayaLayout.createSequentialGroup()
                        .addGroup(InsidPanWilayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InsidPanWilayaLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(AddNewWilayaLab))
                            .addGroup(InsidPanWilayaLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(IconClearSrchWilay, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InsidPanWilayaLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(SearchWilayaTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)))
                .addGroup(InsidPanWilayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsidPanWilayaLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WilayAr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WilayFr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumWily, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(InsidPanWilayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonView4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnUpdtSaveWilaya, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonView5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        ContainairDetaills.add(InsidPanWilaya, "card2");

        InsidPanDaira.setBackground(new java.awt.Color(230, 230, 210));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "حذف", "تعديل", "الوصـف", "الوحـدة", "الرقــم"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setRowHeight(30);
        jTable1.setSelectionBackground(new java.awt.Color(102, 0, 102));
        jTable1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTable1MouseMoved(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("الولاية");

        CmbWilDaira.setBackground(new java.awt.Color(230, 230, 210));
        CmbWilDaira.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CmbWilDaira.setLabeText("");
        ((JLabel)CmbWilDaira.getRenderer()).setHorizontalAlignment(JLabel.CENTER);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("الدائرة");

        NameDaireAR.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NameDaireAR.setForeground(new java.awt.Color(153, 153, 153));
        NameDaireAR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NameDaireAR.setText("الدائرة");
        NameDaireAR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NameDaireARFocusGained(evt);
            }
        });
        NameDaireAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameDaireARActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Daira");

        NameDaireFR.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NameDaireFR.setForeground(new java.awt.Color(153, 153, 153));
        NameDaireFR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NameDaireFR.setText("Daira");
        NameDaireFR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NameDaireFRFocusGained(evt);
            }
        });

        SearchWilayaTXT1.setForeground(new java.awt.Color(204, 204, 204));
        SearchWilayaTXT1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SearchWilayaTXT1.setText("البحث");
        SearchWilayaTXT1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        SearchWilayaTXT1.setLabelText("");
        SearchWilayaTXT1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchWilayaTXT1FocusGained(evt);
            }
        });
        SearchWilayaTXT1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchWilayaTXT1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout InsidPanDairaLayout = new javax.swing.GroupLayout(InsidPanDaira);
        InsidPanDaira.setLayout(InsidPanDairaLayout);
        InsidPanDairaLayout.setHorizontalGroup(
            InsidPanDairaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsidPanDairaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InsidPanDairaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsidPanDairaLayout.createSequentialGroup()
                        .addComponent(SearchWilayaTXT1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(CmbWilDaira, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsidPanDairaLayout.createSequentialGroup()
                        .addGroup(InsidPanDairaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NameDaireFR, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(InsidPanDairaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NameDaireAR, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        InsidPanDairaLayout.setVerticalGroup(
            InsidPanDairaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsidPanDairaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(InsidPanDairaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsidPanDairaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CmbWilDaira, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SearchWilayaTXT1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InsidPanDairaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(InsidPanDairaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameDaireFR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameDaireAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        ContainairDetaills.add(InsidPanDaira, "card2");

        InsidPanCommune.setBackground(new java.awt.Color(230, 230, 210));

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        TableCommune.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        TableCommune.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Code", "البلدية", "Commune"
            }
        ));
        TableCommune.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TableCommune.setGridColor(new java.awt.Color(204, 204, 204));
        TableCommune.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TableCommune.setRowHeight(24);
        TableCommune.setShowVerticalLines(false);
        TableCommune.getTableHeader().setReorderingAllowed(false);
        TableCommune.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableCommuneMouseClicked(evt);
            }
        });
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( SwingConstants.CENTER );

        TableCommune.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        TableCommune.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        TableCommune.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);

        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) TableCommune.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(0);

        TableCommune.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD, 13));
        TableCommune.getTableHeader().setOpaque(false);
        //jTable1.getTableHeader().setBackground(Color.BLACK);
        TableCommune.getTableHeader().setForeground(Color.black);
        jScrollPane1.setViewportView(TableCommune);

        Code_ComLab.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Code_ComLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        SearchTxtCommune.setForeground(new java.awt.Color(204, 204, 204));
        SearchTxtCommune.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        SearchTxtCommune.setText("البحث");
        SearchTxtCommune.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchTxtCommuneFocusGained(evt);
            }
        });
        SearchTxtCommune.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchTxtCommuneKeyReleased(evt);
            }
        });

        CombWilCom.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        CombWilCom.setLabeText("");
        ((JLabel)CombWilCom.getRenderer()).setHorizontalAlignment(JLabel.CENTER);
        CombWilCom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CombWilComItemStateChanged(evt);
            }
        });
        CombWilCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombWilComActionPerformed(evt);
            }
        });

        LabUpdt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        LabUpdt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabUpdt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residence/Image/Edit_Mini_h.png"))); // NOI18N
        LabUpdt.setText("تعديل");
        LabUpdt.setToolTipText("تعديل البلدية");
        LabUpdt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabUpdt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabUpdt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        LabUpdt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabUpdtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabUpdtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabUpdtMouseExited(evt);
            }
        });

        NewCommuneLab.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NewCommuneLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewCommuneLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residence/Image/C_Add_Mini_h.png"))); // NOI18N
        NewCommuneLab.setText("اضافة بلدية");
        NewCommuneLab.setToolTipText("اضافة بلدية جديدة");
        NewCommuneLab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NewCommuneLab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NewCommuneLab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        NewCommuneLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewCommuneLabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewCommuneLabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NewCommuneLabMouseExited(evt);
            }
        });

        NameCommuneAR.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NameCommuneAR.setForeground(new java.awt.Color(153, 153, 153));
        NameCommuneAR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NameCommuneAR.setText("البلدية");
        NameCommuneAR.setBorder(roundedLineBorder);
        NameCommuneAR.setEnabled(false);
        NameCommuneAR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NameCommuneARFocusGained(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("البلدية");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Commune");

        NameCommuneFR.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NameCommuneFR.setForeground(new java.awt.Color(153, 153, 153));
        NameCommuneFR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NameCommuneFR.setText("Commune");
        NameCommuneFR.setEnabled(false);
        NameCommuneFR.setBorder(roundedLineBorder);
        NameCommuneFR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NameCommuneFRFocusGained(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("رمز البلدية");

        CodeCom.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        CodeCom.setForeground(new java.awt.Color(204, 204, 204));
        CodeCom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CodeCom.setText("Code");
        CodeCom.setEnabled(false);
        CodeCom.setBorder(roundedLineBorder);
        CodeCom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CodeComFocusGained(evt);
            }
        });

        BtnSavUpdate.setBackground(new java.awt.Color(0, 102, 102));
        BtnSavUpdate.setForeground(new java.awt.Color(255, 255, 255));
        BtnSavUpdate.setText("حفظ");
        BtnSavUpdate.setBackgroundPainted(true);
        BtnSavUpdate.setEntred(false);
        BtnSavUpdate.setRounded(true);
        BtnSavUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSavUpdateActionPerformed(evt);
            }
        });

        buttonView3.setBackground(new java.awt.Color(0, 102, 102));
        buttonView3.setForeground(new java.awt.Color(255, 255, 255));
        buttonView3.setText("الغاء");
        buttonView3.setBackgroundPainted(true);
        buttonView3.setEntred(false);
        buttonView3.setRounded(true);
        buttonView3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonView3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InsidPanCommuneLayout = new javax.swing.GroupLayout(InsidPanCommune);
        InsidPanCommune.setLayout(InsidPanCommuneLayout);
        InsidPanCommuneLayout.setHorizontalGroup(
            InsidPanCommuneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsidPanCommuneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(InsidPanCommuneLayout.createSequentialGroup()
                .addGroup(InsidPanCommuneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(InsidPanCommuneLayout.createSequentialGroup()
                        .addComponent(Code_ComLab, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NewCommuneLab, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabUpdt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CombWilCom, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchTxtCommune, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(InsidPanCommuneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsidPanCommuneLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsidPanCommuneLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InsidPanCommuneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(InsidPanCommuneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NameCommuneAR, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CodeCom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameCommuneFR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsidPanCommuneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonView3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(BtnSavUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        InsidPanCommuneLayout.setVerticalGroup(
            InsidPanCommuneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsidPanCommuneLayout.createSequentialGroup()
                .addGroup(InsidPanCommuneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsidPanCommuneLayout.createSequentialGroup()
                        .addContainerGap(44, Short.MAX_VALUE)
                        .addGroup(InsidPanCommuneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Code_ComLab)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE))
                    .addGroup(InsidPanCommuneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(InsidPanCommuneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NewCommuneLab)
                            .addGroup(InsidPanCommuneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(InsidPanCommuneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SearchTxtCommune, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CombWilCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addComponent(LabUpdt)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InsidPanCommuneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(InsidPanCommuneLayout.createSequentialGroup()
                        .addComponent(NameCommuneAR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InsidPanCommuneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NameCommuneFR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(InsidPanCommuneLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(40, 40, 40)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(InsidPanCommuneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CodeCom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(InsidPanCommuneLayout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)))))
                .addGap(13, 13, 13)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InsidPanCommuneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSavUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonView3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        ContainairDetaills.add(InsidPanCommune, "card2");

        buttonView2.setBackground(new java.awt.Color(0, 102, 102));
        buttonView2.setForeground(new java.awt.Color(255, 255, 255));
        buttonView2.setText("تعديل");
        buttonView2.setBackgroundPainted(true);
        buttonView2.setEntred(false);
        buttonView2.setRounded(true);
        buttonView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonView2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(RdiBtnCom)
                        .addGap(47, 47, 47)
                        .addComponent(RdiBtnDai)
                        .addGap(42, 42, 42)
                        .addComponent(RdiBtnWil))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonView2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)))
                .addContainerGap())
            .addComponent(ContainairDetaills, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RdiBtnWil, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RdiBtnDai)
                    .addComponent(RdiBtnCom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContainairDetaills, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(buttonView2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 650, 589);
    }// </editor-fold>//GEN-END:initComponents


    private void WilayArFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_WilayArFocusGained
        if (WilayAr.getText().equals("الولاية")) {
            WilayAr.setText("");
            WilayAr.setForeground(Color.black);
            WilayAr.getInputContext().selectInputMethod(new Locale("ar", "DZ"));
        }
    }//GEN-LAST:event_WilayArFocusGained

    private void WilayFrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_WilayFrFocusGained
        if (WilayFr.getText().equals("Wilaya")) {
            WilayFr.setText("");
            WilayFr.setForeground(Color.black);
            WilayFr.getInputContext().selectInputMethod(new Locale("fr", "FR"));
        }
    }//GEN-LAST:event_WilayFrFocusGained

    private void WilayArFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_WilayArFocusLost
        if (WilayAr.getText().equals("")) {
            WilayAr.setText("الولاية");
            WilayAr.setForeground(Color.gray);
        }
    }//GEN-LAST:event_WilayArFocusLost

    private void NumWilyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NumWilyFocusGained
        if (NumWily.getText().equals("الرقم")) {
            NumWily.setText("");
            NumWily.setForeground(Color.black);
            
        }
    }//GEN-LAST:event_NumWilyFocusGained

    private void buttonView7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonView7ActionPerformed

    private void buttonView8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonView8ActionPerformed

    private void BtnSavUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSavUpdateActionPerformed

        if (RdiBtnWil.isSelected()) {

        } else if (RdiBtnDai.isSelected()) {

//            if (NameDaireAR.getText().equals("الدائرة") || NameDaireAR.getText().equals("")
//                    || NameDaireFR.getText().equals("Daira") || NameDaireFR.getText().equals("")
//                    || CmbWilDaira.getSelectedIndex() == 0) {
//                JOptionPane.showMessageDialog(null, "تأكد من تعبئة المعلومات");
//            } else {
//                InsertWilaya(WilayAr.getText(), WilayFr.getText(), Integer.parseInt(NumWily.getText()));
//                //cnf.Filling_Wilay_In_Other();
//                //cnf.Filling_NameWilaya();
//                NameDaireAR.setText("");
//                NameDaireFR.setText("");
//                CmbWilDaira.setSelectedIndex(0);
//            }
        } else {

            String TxtBtn = BtnSavUpdate.getText();

            switch (TxtBtn) {
                case "حفظ":  // Choice of save New Commune
                    if (NameCommuneAR.getText().equals("البلدية") || NameCommuneAR.getText().equals("")
                            || NameCommuneFR.getText().equals("Commune") || NameCommuneFR.getText().equals("")
                            || CombWilCom.getSelectedIndex() == 0) {
                        JOptionPane.showMessageDialog(null, "تأكد من تعبئة المعلومات");
                    } else {
                        int idWilaya = Fill_Data.GetId_From_DB("ID_Wilaya", "Wilaya", "NameWilaya", (String) CombWilCom.getSelectedItem());
                        InsertCommune(CodeCom.getText(), NameCommuneAR.getText(), NameCommuneFR.getText(), idWilaya, 0);
                        FillTableCommune_Combobox((String) CombWilCom.getSelectedItem(), TableCommune, null, 0);
                        CodeCom.setText("Code");
                        NameCommuneAR.setText("البلدية");
                        NameCommuneFR.setText("Commune");
                        //cnf.Filling_NameWilaya();
                        CombWilCom.setSelectedIndex(0);
                    }
                    break;
                // save Update data of Commune
                case "حفظ التعديلات":
                    int n = JOptionPane.showConfirmDialog(null, "هل تريد حفظ التعديلات على البلدية", "عملية التعديل", JOptionPane.YES_NO_OPTION);
                    if (n == 0) {
                        int idWilaya = Fill_Data.GetId_From_DB("ID_Wilaya", "Wilaya", "NameWilaya", (String) CombWilCom.getSelectedItem());
                        InsertCommune(CodeCom.getText(), NameCommuneAR.getText(), NameCommuneFR.getText(), idWilaya, 1);
                        FillTableCommune_Combobox((String) CombWilCom.getSelectedItem(), TableCommune, null, 0);
//                        CodeCom.setText("Code");
//                        NameCommuneAR.setText("البلدية");
//                        NameCommuneFR.setText("Commune");
//                        Code_ComLab.setText("");

                        Code_ComLab.setText("");
                    }
                    break;
            }
            EnableFieldCommune(false);
            InitialiseFieldCommune();
        }


    }//GEN-LAST:event_BtnSavUpdateActionPerformed

    private void RdiBtnDaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdiBtnDaiActionPerformed
        if (RdiBtnDai.isSelected()) {
            InsidPanDaira.setVisible(true);
            InsidPanCommune.setVisible(false);
            InsidPanWilaya.setVisible(false);
            //PanDaira.setBackground(Color.white);
//            if (!PanDaira.isEnabled()) {
//                //PanDaira.setEnabled(true);
//                Disable_Enable_Compenents(PanDaira, true);
//            }
//            Disable_Enable_Compenents(PanWilaya, false);
//            Disable_Enable_Compenents(PanCommune, false);
//           PanWilaya.setEnabled(false);
//           PanCommune.setEnabled(false);
        }
    }//GEN-LAST:event_RdiBtnDaiActionPerformed

    private void NameCommuneARFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameCommuneARFocusGained
        if (NameCommuneAR.getText().equals("البلدية")) {
            NameCommuneAR.setText("");
            NameCommuneAR.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_NameCommuneARFocusGained

    private void NameCommuneFRFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameCommuneFRFocusGained
        if (NameCommuneFR.getText().equals("Commune")) {
            NameCommuneFR.setText("");
            NameCommuneFR.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_NameCommuneFRFocusGained

    private void NameDaireARFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameDaireARFocusGained
        // TODO add your handling code here:
        if (NameDaireAR.getText().equals("الدائرة")) {
            NameDaireAR.setText("");
            NameDaireAR.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_NameDaireARFocusGained

    private void NameDaireFRFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameDaireFRFocusGained
        if (NameDaireFR.getText().equals("Daira")) {
            NameDaireFR.setText("");
            NameDaireFR.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_NameDaireFRFocusGained

    private void RdiBtnWilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdiBtnWilActionPerformed
        if (RdiBtnWil.isSelected()) {
            InsidPanWilaya.setVisible(true);

            InsidPanCommune.setVisible(false);
            InsidPanDaira.setVisible(false);

//            //PanWilaya.setBackground(new Color(255, 255, 255));
//            if (!PanWilaya.isEnabled()) {
//                  //PanWilaya.setEnabled(true);
//                  Disable_Enable_Compenents(PanWilaya, true);
//            }
////            PanDaira.setEnabled(false);
////            PanCommune.setEnabled(false);
//            Disable_Enable_Compenents(PanDaira, false);
//            Disable_Enable_Compenents(PanCommune, false);
        }
    }//GEN-LAST:event_RdiBtnWilActionPerformed

    private void RdiBtnComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdiBtnComActionPerformed
        if (RdiBtnCom.isSelected()) {

            InsidPanCommune.setVisible(true);
            InsidPanDaira.setVisible(false);
            InsidPanWilaya.setVisible(false);

            //FillTableCommune_Combobox((String) CombWilCom.getSelectedItem(), TableCommune, null, 0);
//            if (!PanCommune.isEnabled()) {
//                //PanCommune.setEnabled(true);
//                Disable_Enable_Compenents(PanCommune, true);
//            }
//            
//            Disable_Enable_Compenents(PanDaira, false);
//            Disable_Enable_Compenents(PanWilaya, false);
//            PanDaira.setEnabled(false);
//            PanWilaya.setEnabled(false);
        }
    }//GEN-LAST:event_RdiBtnComActionPerformed

    private void NameDaireARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameDaireARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameDaireARActionPerformed

    private void TableCommuneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableCommuneMouseClicked

        if (NewUpdateCommuneChoice == 1) {
            // Clicked when add New Commune 
            // send msg to user to continue or canceled this opeartion 
            int n = JOptionPane.showConfirmDialog(null,
                    "هل تريد الغاء عملية الاضافة",
                    "تأكيد العملية", JOptionPane.YES_NO_OPTION);
            if (n == 0) {
                System.out.println("");
                EnableFieldCommune(false);
                InitialiseFieldCommune();
                
            }

        } else {
            int slcRow = TableCommune.getSelectedRow();
            CodeCom.setText((String) TableCommune.getValueAt(slcRow, 0));
            int idComm = GetId_Commune(CodeCom.getText());

            Code_ComLab.setText(idComm + ""); //id Of Commune

            NameCommuneAR.setText((String) TableCommune.getValueAt(slcRow, 1));
            NameCommuneFR.setText((String) TableCommune.getValueAt(slcRow, 2));
        }

    }//GEN-LAST:event_TableCommuneMouseClicked

    private void CodeComFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CodeComFocusGained
        if (CodeCom.getText().equals("Code")) {
            CodeCom.setText("");
        }
    }//GEN-LAST:event_CodeComFocusGained

    private void CombWilComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombWilComActionPerformed
        // FillTableCommune_Combobox((String) CombWilCom.getSelectedItem(), TableCommune, null, 0);
    }//GEN-LAST:event_CombWilComActionPerformed

    private void buttonView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView2ActionPerformed
        int n = JOptionPane.showConfirmDialog(null,
                "هل تريد تعديل على البلدية",
                "عملية التعديل", JOptionPane.YES_NO_OPTION);
        if (n == 0) {
            int idWilaya = Fill_Data.GetId_From_DB("ID_Wilaya", "Wilaya", "NameWilaya", (String) CombWilCom.getSelectedItem());

            InsertCommune(CodeCom.getText(), NameCommuneAR.getText(), NameCommuneFR.getText(), idWilaya, 1);

            FillTableCommune_Combobox((String) CombWilCom.getSelectedItem(), TableCommune, null, 0);
            CodeCom.setText("Code");
            NameCommuneAR.setText("البلدية");
            NameCommuneFR.setText("Commune");
            Code_ComLab.setText("");
        } else {
            CodeCom.setText("Code");
            NameCommuneAR.setText("البلدية");
            NameCommuneFR.setText("Commune");
            Code_ComLab.setText("");
        }
    }//GEN-LAST:event_buttonView2ActionPerformed

    private void buttonView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView3ActionPerformed
        InitialiseFieldCommune();
        EnableFieldCommune(false);
        NewUpdateCommuneChoice = 0;
    }//GEN-LAST:event_buttonView3ActionPerformed

    private void LabUpdtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabUpdtMouseClicked

        if (!(NameCommuneFR.getText().equals("Commune") && NameCommuneAR.getText().equals("البلدية") && CodeCom.getText().equals("Code"))) {
            // && JOptionPane.showConfirmDialog(null,"هل تريد تعديل على البلدية","عملية التعديل", JOptionPane.YES_NO_OPTION)==0 

            NameCommuneFR.setForeground(Color.black);

            NameCommuneAR.setForeground(Color.black);

            CodeCom.setForeground(Color.black);

            EnableFieldCommune(true);

            NewUpdateCommuneChoice = 2;//   = 2 uses for Update Commune  
            BtnSavUpdate.setText("حفظ التعديلات");

        }
    }//GEN-LAST:event_LabUpdtMouseClicked
    int NewUpdateCommuneChoice = 0; // This variabe use to select btn of save data of commune or update
    private void NewCommuneLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewCommuneLabMouseClicked

        if ((NameCommuneFR.getText().equals("Commune") && NameCommuneAR.getText().equals("البلدية") && CodeCom.getText().equals("Code"))) {
            NameCommuneFR.setForeground(Color.black);
            NameCommuneAR.setForeground(Color.black);
            CodeCom.setForeground(Color.black);
            EnableFieldCommune(true);
        } else {
            InitialiseFieldCommune();
        }
        NewUpdateCommuneChoice = 1;//   = 1 uses for save new Commune  
        BtnSavUpdate.setText("اضافة البلدية الجديدة");

    }//GEN-LAST:event_NewCommuneLabMouseClicked

    private void CombWilComItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CombWilComItemStateChanged
        FillTableCommune_Combobox((String) CombWilCom.getSelectedItem(), TableCommune, null, 0);
        InitialiseFieldCommune();
        EnableFieldCommune(false);

    }//GEN-LAST:event_CombWilComItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened


    }//GEN-LAST:event_formWindowOpened

    private void LabUpdtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabUpdtMouseEntered
        LabUpdt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residence/Image/Edit_Mini.png"))); // NOI18N
    }//GEN-LAST:event_LabUpdtMouseEntered

    private void LabUpdtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabUpdtMouseExited
        LabUpdt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residence/Image/Edit_Mini_h.png"))); // NOI18N
    }//GEN-LAST:event_LabUpdtMouseExited

    private void NewCommuneLabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewCommuneLabMouseEntered
        NewCommuneLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residence/Image/C_Add_Mini.png"))); // NOI18N
    }//GEN-LAST:event_NewCommuneLabMouseEntered

    private void NewCommuneLabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewCommuneLabMouseExited
        NewCommuneLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residence/Image/C_Add_Mini_h.png"))); // NOI18N
    }//GEN-LAST:event_NewCommuneLabMouseExited

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (this.chouceGui == 1) {
            this.home.FillDataOfWilayaAndCommuneInHome();
        } else {
            this.conf.FillingWilayInFormConf();
        }
    }//GEN-LAST:event_formWindowClosed

    private void jTable1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseMoved

        int col = jTable1.columnAtPoint(evt.getPoint());
        //int row=jTable1.rowAtPoint(evt.getPoint());

        Cursor handCursor = Cursor.getPredefinedCursor(Cursor.HAND_CURSOR);
        Cursor DefaultCursor = Cursor.getDefaultCursor();

        switch (col) {
            case 0:
            case 1:
                //JOptionPane.showMessageDialog(null, "Col :"+jTable1.getSelectedColumn() +" === Row : "+jTable1.getSelectedRow());
                jTable1.setCursor(handCursor);
                break;

            default:
                jTable1.setCursor(DefaultCursor);
                break;
        }
    }//GEN-LAST:event_jTable1MouseMoved

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
//        int col = jTable1.columnAtPoint(evt.getPoint());
//        int row = jTable1.rowAtPoint(evt.getPoint());
//        DefaultTableModel defMdl = (DefaultTableModel) jTable1.getModel();
//        int IdOrder = (int) jTable1.getValueAt(row, 4);
//        byte conf;
//        switch (col) {
//            case 0:
//            UnitCnfMsg.SetMsgTextShow("هل تريد حذف الوحدة");
//            dialgMsgUnits.ShowmessgConf();
//            //           int Conf=JOptionPane.showConfirmDialog(this, "Confirm Delete data","Confirm ", JOptionPane.YES_NO_OPTION);
//            //           JOptionPane.showMessageDialog(null, Conf);
//
//            conf = dialgMsgUnits.getYes_No();
//            if (conf == 1) {
//                int valCon = unit_getData.DeleteUnit(IdOrder);
//                if (valCon > 0) {
//                    defMdl.removeRow(row); //add Mesg information data;
//                }
//            }
//            // Function Delete Categorie
//            //JOptionPane.showMessageDialog(null, "Col :"+jTable1.getSelectedColumn() +" === Row : "+jTable1.getSelectedRow());
//            break;
//            case 1:
//            UnitCnfMsg.SetMsgTextShow("هل تريد تعديل الوحدة");
//            dialgMsgUnits.ShowmessgConf();
//            conf = dialgMsgUnits.getYes_No();
//            if (conf == 1) {
//                Unit_Desc.setText((String) jTable1.getValueAt(row, 2));
//                Unit_Nam.setText((String) jTable1.getValueAt(row, 3));
//                int OrderUnit = (int) jTable1.getValueAt(row, 4);
//                LstOrd_Unit.setText((int) jTable1.getValueAt(row, 4) + "");
//                if (unit_getData.GetTypeUnite(OrderUnit) == 1) {
//                    ManyPiece.setSelected(true);
//
//                } else {
//                    OnePiece.setSelected(true);
//                }
//            }
//            break;
//        }
    }//GEN-LAST:event_jTable1MouseClicked

    public void FillTableWilaya(JTable tableUnit) {
        // SELECT ALL UNIT TO DISPLAY DATA
        String Query;
        Statement stm;
        ResultSet res;
        Query = "SELECT * FROM Wilaya WHERE NumWilaya != '0'";
        DefaultTableModel dfTab = (DefaultTableModel) tableUnit.getModel();
        dfTab.setRowCount(0);
        cnx.Connecting();
        try {

            stm = cnx.getConnect().createStatement();
            res = stm.executeQuery(Query);
            Object arg[] = new Object[6];

            while (res.next()) {
                arg[0] = new ImageIcon(getClass().getResource("/residence/Image/Delete_Mini_h.png"));
                arg[1] = new ImageIcon(getClass().getResource("/residence/Image/Edit_Mini.png"));
                arg[2] = new ImageIcon(getClass().getResource("/residence/Image/C_Add_MiniSize.png"));
                //arg[2]=new ImageIcon(getClass().getResource("/imgs/C_Add_Mini_h.png")); 
                arg[3] = res.getString("DescWilaya");
                arg[4] = res.getString("NameWilaya");
                arg[5] = res.getString("NumWilaya");

                dfTab.addRow(arg);
            }
            tableUnit.setModel(dfTab);  // add model in my -table

            stm.close(); // Closed Connection && res
            res.close(); //

            cnx.Deconnect(); //Deconnect Connection 

        } catch (SQLException e) {
            // Display Error Exception 

            e.printStackTrace();
        }
    }

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseEntered

    private void TableWilayaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableWilayaMouseMoved
        int col = TableWilaya.columnAtPoint(evt.getPoint());
        //int row=jTable1.rowAtPoint(evt.getPoint());

        Cursor handCursor = Cursor.getPredefinedCursor(Cursor.HAND_CURSOR);
        Cursor DefaultCursor = Cursor.getDefaultCursor();

        switch (col) {
            case 0:
            case 1:
            case 2:
                //JOptionPane.showMessageDialog(null, "Col :"+jTable1.getSelectedColumn() +" === Row : "+jTable1.getSelectedRow());
                TableWilaya.setCursor(handCursor);
                break;

            default:
                TableWilaya.setCursor(DefaultCursor);
                break;
        }
    }//GEN-LAST:event_TableWilayaMouseMoved
    private int IdOrder;

    private void TableWilayaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableWilayaMouseClicked
        /**
         * Col=0 for delete Wilaya Col=1 for update Wilaya Col=2 For insert New
         * Wilaya
         */

        int col = TableWilaya.columnAtPoint(evt.getPoint());
        int row = TableWilaya.rowAtPoint(evt.getPoint());
        //DefaultTableModel defMdl = (DefaultTableModel) TableWilaya.getModel();
        //IdOrder = (int) TableWilaya.getValueAt(row, 5);
        int Conf;
        switch (col) {

            case 0:
                Conf = JOptionPane.showConfirmDialog(this, "هل تريد حذف الولاية ", "Confirm ", JOptionPane.YES_NO_OPTION);
//              JOptionPane.showMessageDialog(null, Conf);
                if (Conf == 0) {
                    String WilFR = (String) TableWilaya.getValueAt(row, 3);
                    WilayAr.setText(WilFR);
                    String WilAR = (String) TableWilaya.getValueAt(row, 4);
                    WilayFr.setText(WilAR);
                    String WilNum = (String) TableWilaya.getValueAt(row, 5);
                    NumWily.setText(WilNum);
                    IdOrder = Fill_Data.GetId_From_DB("ID_Wilaya", "Wilaya", "NameWilaya", WilAR);// IdOrder for use in query 
                    // in fun Insert_Update_Delete_Wilaya(...)
                    Insert_Update_Delete_Wilaya("", "", 0, 0); // choice == 0 for deletion
                }
                break;

            case 1:
                Conf = JOptionPane.showConfirmDialog(this, "هل تريد تعديل المعطيات", "Confirm ", JOptionPane.YES_NO_OPTION);
//              JOptionPane.showMessageDialog(null, Conf);ب
                if (Conf == 0) {

                    String WilFR = (String) TableWilaya.getValueAt(row, 3);
                    WilayAr.setText(WilFR);
                    WilayAr.setForeground(Color.black);
                    WilayAr.requestFocus();
                    String WilAR = (String) TableWilaya.getValueAt(row, 4);
                    WilayFr.setText(WilAR);
                    WilayFr.setForeground(Color.black);
                    String WilNum = (String) TableWilaya.getValueAt(row, 5);
                    NumWily.setText(WilNum);
                    NumWily.setForeground(Color.black);
                    IdOrder = Fill_Data.GetId_From_DB("ID_Wilaya", "Wilaya", "NameWilaya", WilAR);// IdOrder for use in query 
                    // in fun Insert_Update_Delete_Wilaya(...)

                    HintToUser.setText("قم بالتعديل على الولاية");
                    //HintToUser.setForeground(Color.red);

                    BtnUpdtSaveWilaya.setText("حفظ التعديلات");
                }
                break;
            case 2:
                WilayAr.setText("");
                WilayAr.setForeground(Color.black);
                WilayFr.setText("");
                WilayFr.setForeground(Color.black);
                NumWily.setText("");
                NumWily.setForeground(Color.black);
                HintToUser.setText("قم باضافة ولاية جديدة");
                //HintToUser.setForeground(Color.red);
                break;
        }


    }//GEN-LAST:event_TableWilayaMouseClicked

    private void TableWilayaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableWilayaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TableWilayaMouseEntered

    private void buttonView4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView4ActionPerformed
        this.InitialiseFieldsOfWilay();
        TableWilaya.getSelectionModel().clearSelection();
        SearchWilayaTXT.setText("البحث");
        SearchWilayaTXT.setForeground(Color.black);
        FilterDataIntable("", TableWilaya, (DefaultTableModel) TableWilaya.getModel());
        HintToUser.setText("");
        IdOrder = 0;

//this.dispose();

    }//GEN-LAST:event_buttonView4ActionPerformed

    public void InitialiseFieldsOfWilay() {
        WilayAr.setText("الولاية");
        WilayAr.setForeground(Color.gray);
        WilayFr.setText("Wilaya");
        WilayFr.setForeground(Color.gray);
        NumWily.setText("الرقم");
        NumWily.setForeground(Color.gray);
    }

    private void BtnUpdtSaveWilayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdtSaveWilayaActionPerformed
        if (WilayAr.getText().equals("الولاية") || WilayAr.getText().equals("")
                || WilayFr.getText().equals("Wilaya") || WilayFr.getText().equals("")
                || NumWily.getText().equals("الرقم") || NumWily.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "تأكد من تعبئة المعلومات");
        } else {

            //Insert(WilayAr.getText(), WilayFr.getText(), Integer.parseInt(NumWily.getText()),1);//
            //cnf.Filling_NameWilaya();
            if (BtnUpdtSaveWilaya.getText().equals("حفظ")) {
                Insert_Update_Delete_Wilaya(WilayAr.getText(), WilayFr.getText(), Integer.parseInt(NumWily.getText()), 2);
            } else {
                Insert_Update_Delete_Wilaya(WilayAr.getText(), WilayFr.getText(), Integer.parseInt(NumWily.getText()), 1);

            }

        }
    }//GEN-LAST:event_BtnUpdtSaveWilayaActionPerformed

    private void SearchTxtCommuneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTxtCommuneKeyReleased
        FilterDataIntable(SearchTxtCommune.getText(), TableCommune, (DefaultTableModel) TableCommune.getModel());
    }//GEN-LAST:event_SearchTxtCommuneKeyReleased

    private void SearchTxtCommuneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchTxtCommuneFocusGained
        if (SearchTxtCommune.getText().equals("البحث")) {
            SearchTxtCommune.setText("");
            SearchTxtCommune.setForeground(Color.black);
        }
    }//GEN-LAST:event_SearchTxtCommuneFocusGained

    private void SearchWilayaTXTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchWilayaTXTFocusGained
        if (SearchWilayaTXT.getText().equals("البحث")) {
            SearchWilayaTXT.setText("");
            SearchWilayaTXT.setForeground(Color.black);
        }
    }//GEN-LAST:event_SearchWilayaTXTFocusGained

    private void SearchWilayaTXTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchWilayaTXTKeyReleased
        
        if(!SearchWilayaTXT.getText().equals("")){
            FilterDataIntable(SearchWilayaTXT.getText(), TableWilaya, (DefaultTableModel) TableWilaya.getModel());
        
        IconClearSrchWilay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residence/Image/iconsCls.png"))); // NOI18N
        }else{ 
            
            IconClearSrchWilay.setIcon(null); // NOI18N
            FilterDataIntable(SearchWilayaTXT.getText(), TableWilaya, (DefaultTableModel) TableWilaya.getModel());
        }
        

    }//GEN-LAST:event_SearchWilayaTXTKeyReleased

    private void SearchWilayaTXT1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchWilayaTXT1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchWilayaTXT1FocusGained

    private void SearchWilayaTXT1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchWilayaTXT1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchWilayaTXT1KeyReleased

    private void buttonView5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView5ActionPerformed
        this.home.FillDataOfWilayaAndCommuneInHome();
        HintToUser.setText("");
        //HintToUser.setForeground(Color.red);
        this.dispose();

    }//GEN-LAST:event_buttonView5ActionPerformed

    private void AddNewWilayaLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewWilayaLabMouseClicked

        if(JOptionPane.showConfirmDialog(this, "هل تريد اضافة ولاية جديدة", "عملية تأكيد ", JOptionPane.YES_NO_OPTION)==0){
           WilayAr.setText("");
           WilayAr.setForeground(Color.black);
           WilayAr.requestFocus();
           WilayFr.setText("");
           WilayFr.setForeground(Color.black);
           NumWily.setText("");
           NumWily.setForeground(Color.black);
           HintToUser.setText("قم باضافة ولاية جديدة");
         
        }
         
        
    }//GEN-LAST:event_AddNewWilayaLabMouseClicked

    private void AddNewWilayaLabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewWilayaLabMouseEntered
        AddNewWilayaLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residence/Image/C_Add_Mini.png")));
    }//GEN-LAST:event_AddNewWilayaLabMouseEntered

    private void AddNewWilayaLabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewWilayaLabMouseExited
        AddNewWilayaLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residence/Image/C_Add_Mini_h.png"))); // NOI18N
    }//GEN-LAST:event_AddNewWilayaLabMouseExited

    private void WilayFrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_WilayFrFocusLost
        if (WilayFr.getText().equals("")) {
            WilayFr.setText("Wilaya");
            WilayFr.setForeground(Color.gray);
        }
    }//GEN-LAST:event_WilayFrFocusLost

    private void NumWilyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NumWilyFocusLost
        if (NumWily.getText().equals("")) {
            NumWily.setText("الرقم");
            NumWily.setForeground(Color.gray);
        }
    }//GEN-LAST:event_NumWilyFocusLost

    private void SearchWilayaTXTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchWilayaTXTFocusLost
        if(SearchWilayaTXT.getText().equals("")){
            IconClearSrchWilay.setIcon(null);
            SearchWilayaTXT.setText("البحث");
            SearchWilayaTXT.setForeground(Color.gray);
        }
    }//GEN-LAST:event_SearchWilayaTXTFocusLost

    private void IconClearSrchWilayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconClearSrchWilayMouseClicked
        SearchWilayaTXT.setText("");
        FilterDataIntable("", TableWilaya, (DefaultTableModel) TableWilaya.getModel());
        //FillTableWilaya(TableWilaya);
    }//GEN-LAST:event_IconClearSrchWilayMouseClicked

    public void InitialiseFieldCommune() {
        CodeCom.setText("Code");
        NameCommuneAR.setText("البلدية");
        NameCommuneFR.setText("Commune");
    }

    public void EnableFieldCommune(boolean CaseTxt) {
        CodeCom.setEnabled(CaseTxt);
        NameCommuneAR.setEnabled(CaseTxt);
        NameCommuneFR.setEnabled(CaseTxt);

    }

    public void Disable_Enable_Compenents(JPanel panel, boolean tcase) {
        Component[] components = panel.getComponents();
        for (Component component : components) {
            component.setEnabled(tcase);
        }
    }

    public void Insert_Update_Delete_Wilaya(String WilayaAR, String WilayaFR, int NumWilaya, int choice) {
        //  String replace;
        /**
         * *
         * 0 - insert Wilaya 1- update Wilaya 2- Delete Wilaya
         *
         */
        String Query = null;
        if (WilayaFR.contains("'")) {
            WilayaFR = WilayaFR.replace("'", "");
        }
        int idWilaya;

        switch (choice) {
            case 2:
                Query = "insert into Wilaya (NameWilaya,DescWilaya,NumWilaya) values (N'" + WilayaAR + "','" + WilayaFR + "'," + NumWilaya + ")";
                break;
            case 1:
                // Update data of  Wilaya
                //Query = "insert into Wilaya (NameWilaya,DescWilaya,NumWilaya) values (N'" + WilayaAR + "','" + WilayaFR + "'," + NumWilaya + ")";
                // get id Of wilaya

                //idWilaya = Fill_Data.GetId_From_DB("ID_Wilaya", "Wilaya", "NameWilaya", WilayAr.getText());
                Query = "update  Wilaya SET NameWilaya=N'" + WilayaAR + "' ,DescWilaya=N'" + WilayaFR + "',NumWilaya='" + NumWilaya + "' where ID_Wilaya=" + IdOrder + ";";
                break;
            case 0:
                //idWilaya = Fill_Data.GetId_From_DB("ID_Wilaya", "Wilaya", "NameWilaya", WilayAr.getText());
                Query = "DELETE FROM Wilaya WHERE  ID_Wilaya=" + IdOrder + "";
                break;
            default:
                break;
        }

        PreparedStatement prstm;
        //ResultSet res=null;
        cnx.Connecting();
        try {
            prstm = cnx.getConnect().prepareStatement(Query);
            int x = prstm.executeUpdate();
            if (x > 0) {
                System.out.println("insert Success..");
                String MsgWlyOperation = "";
                switch (choice) {
                    case 2:
                        MsgWlyOperation = "تمت الاضافة بنجاح";
                        break;
                    case 1:
                        MsgWlyOperation = "تم التعديل بنجاح";
                        break;
                    default:
                        MsgWlyOperation = "تم الخذف بنجاح";
                        break;
                }

                JOptionPane.showMessageDialog(null, MsgWlyOperation);

                FillTableWilaya(TableWilaya);
                InitialiseFieldsOfWilay();
                HintToUser.setText("");
            } else {
                System.out.println("insert Failed..");
            }

            prstm.close();
            cnx.Deconnect();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void InsertCommune(String Code_commune, String Commune_Ar, String Commune_Fr, int ID_Wilaya, int choice) {
        PreparedStatement prstm;
        String Query = "insert into Commune (Code_commune,Commune_Ar,Commune_Fr,ID_Wilaya) values "
                + "('" + Code_commune + "' , N'" + Commune_Ar + "' ,'" + Commune_Fr + "'," + ID_Wilaya + ");";

        //QueryUpdt="update  Commune set Code_commune='"+Code_commune+"' ,Commune_Ar=N'"+Commune_Ar+"',Commune_Fr='"+Commune_Fr+"' where ID_Wilaya="+ID_Wilaya+";";
        if (choice == 1) {

            // int id_Commune=GetId_Commune();
            int id_Commune = Integer.parseInt(Code_ComLab.getText());
            Query = "update  Commune SET Code_commune='" + Code_commune + "' ,Commune_Ar=N'" + Commune_Ar + "',Commune_Fr='" + Commune_Fr + "' where id_Commune=" + id_Commune + ";";

        }

        cnx.Connecting();
        try {
            prstm = cnx.getConnect().prepareStatement(Query);
            int x = prstm.executeUpdate();
            System.out.println("Insert Query  Executed..");
            if (x > 0) {

                System.out.println((choice == 1) ? "Success Update Commune" : "Success add Commune ");
            } else {
                System.out.println("Failed Commune Added");
            }
            prstm.close();
            cnx.Deconnect();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void deleteCommune() {
//    int typ=0;
//        //JOptionPane.showMessageDialog(null, "The word is :"+val);
//        if (val.equals("الاقامةالجامعية")) {
//         typ=1;   
//        }else typ=2;
//        
        //JOptionPane.showMessageDialog(null, "The value  is :"+typ);
        int id_commune = Integer.parseInt(Code_ComLab.getText());
        String Del = "delete from Commune where id_Commune=" + id_commune + " ";
        PreparedStatement prstm = null;
        cnx.Connecting();
        try {
            prstm = cnx.getConnect().prepareStatement(Del);
            int x = prstm.executeUpdate();
            if (x > 0) {
                //JOptionPane.showMessageDialog(null, "Succeful Delete..");
                FillTableCommune_Combobox((String) CombWilCom.getSelectedItem(), jTable1, null, 0);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error in delete Commune :" + e.getMessage());
        }
        try {
            prstm.close();
            cnx.Deconnect();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void FillTableCommune_Combobox(String Wly, JTable tab, JComboBox cmb, int choice) {

        //dfm=(DefaultTableModel)jTable2.getModel();
        String Query = "SELECT * FROM Commune,Wilaya where Commune.ID_Wilaya=Wilaya.ID_Wilaya "
                + " AND Wilaya.NameWilaya=N'" + Wly + "' ;";

        Statement stm = null;
        ResultSet Res = null;
        cnx.Connecting();
        if (choice == 0) {
            //DefaultTableModel dfm=new DefaultTableModel();
            DefaultTableModel dfm = (DefaultTableModel) tab.getModel();
            dfm.setRowCount(0);
//    dfm.addColumn("Code");
//    
//    dfm.addColumn("البلدية");
//    dfm.addColumn("Commune");
            try {
                stm = cnx.getConnect().createStatement();
                Res = stm.executeQuery(Query);
                System.out.println("Run query passed");
                while (Res.next()) {
                    Object arg[] = {Res.getString("Code_commune"), Res.getString("Commune_Ar"), Res.getString("Commune_Fr")};
                    //System.out.println("Arg:"+arg.toString());         
                    dfm.addRow(arg);
                }
                tab.setModel(dfm);

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error In Fill Table Of managers " + e.getMessage());

            }

        } else {
            DefaultComboBoxModel Dfcmb = new DefaultComboBoxModel();
            Dfcmb = (DefaultComboBoxModel) cmb.getModel();
            Dfcmb.removeAllElements();
            try {
                stm = cnx.getConnect().createStatement();
                Res = stm.executeQuery(Query);
                Dfcmb.addElement("اختر البلدية");
                while (Res.next()) {
                    Dfcmb.addElement(Res.getString("Commune_Ar"));
                }
                cmb.setModel(Dfcmb);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error In Fill Table Of managers " + e.getMessage());

            }

        }
        try {
            stm.close();
            Res.close();
            cnx.Deconnect();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error In Close Statement" + e.getMessage());
        }
    }

    public int GetId_Commune(String Code_commune) {
        int Id_Commune = 0;
        String Query = "select id_Commune FROM Commune WHERE Code_commune='" + Code_commune + "' ";
        Statement stm;
        ResultSet res;
        cnx.Connecting();
        try {
            stm = cnx.getConnect().createStatement();
            res = stm.executeQuery(Query);
            if (res.next()) {
                Id_Commune = res.getInt("id_Commune");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error In Get Id Commune" + e.getMessage());
        }
        return Id_Commune;
    }

    /**
     * ********************************************************
     */
    public void FilterDataIntable(String Query, JTable tab, DefaultTableModel dm) {  //filtrer dans le tableau fournisseur
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dm);
        tab.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(Query));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddWilaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddWilaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddWilaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddWilaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AddWilaya(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddNewWilayaLab;
    private View.ButtonView BtnSavUpdate;
    private View.ButtonView BtnUpdtSaveWilaya;
    private View.Combobox CmbWilDaira;
    private javax.swing.JTextField CodeCom;
    private javax.swing.JLabel Code_ComLab;
    private View.Combobox CombWilCom;
    private javax.swing.JPanel ContainairDetaills;
    private javax.swing.JLabel HintToUser;
    private javax.swing.JLabel IconClearSrchWilay;
    private javax.swing.JPanel InsidPanCommune;
    private javax.swing.JPanel InsidPanDaira;
    private javax.swing.JPanel InsidPanWilaya;
    private javax.swing.JLabel LabUpdt;
    private javax.swing.JTextField NameCommuneAR;
    private javax.swing.JTextField NameCommuneFR;
    private javax.swing.JTextField NameDaireAR;
    private javax.swing.JTextField NameDaireFR;
    private javax.swing.JLabel NewCommuneLab;
    private javax.swing.JTextField NumWily;
    private javax.swing.JRadioButton RdiBtnCom;
    private javax.swing.JRadioButton RdiBtnDai;
    private javax.swing.JRadioButton RdiBtnWil;
    private javax.swing.JTextField SearchTxtCommune;
    private View.TextField SearchWilayaTXT;
    private View.TextField SearchWilayaTXT1;
    private javax.swing.JTable TableCommune;
    private javax.swing.JTable TableWilaya;
    private javax.swing.JTextField WilayAr;
    private javax.swing.JTextField WilayFr;
    private View.ButtonView buttonView2;
    private View.ButtonView buttonView3;
    private View.ButtonView buttonView4;
    private View.ButtonView buttonView5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
