/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residence;

import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Basma01
 */
public class Guest1 extends javax.swing.JFrame {

    Resident_Gl Resident_GlRemplissage = new Resident_Gl();
    Student_Res student_Res;
    Guest guestRmpissage = new Guest();
    Guest guest;
    MessageErrorControl messagerror;
    Get_Info_DB Fill_Data=new Get_Info_DB();
    settings setting=new settings();

    public Guest1() {
        initComponents();
        LabGuest.setVisible(false);
        BtnSaveStd8.setVisible(false);
        BtnSaveStd7.setVisible(false);
        PanReception.setVisible(true);
        PanGuests.setVisible(false);
        jLabel161.setBackground(new Color(0, 190, 190));
        Resident_GlRemplissage.DisplayAllResidentInTableGuest(TablStd);
        this.setLocationRelativeTo(null);
        ChgeCntAcess_FcTxtBrcd();
        
        Toolkit.getDefaultToolkit().setLockingKeyState(KeyEvent.VK_CAPS_LOCK, true);
        
        TablGest.setAutoResizeMode(TablGest.AUTO_RESIZE_OFF);
        TablGest.getColumnModel().getColumn(8).setPreferredWidth(30);
        TablGest.getColumnModel().getColumn(7).setPreferredWidth(30);
        TablGest.getColumnModel().getColumn(2).setPreferredWidth(50);
        TablStd.getColumnModel().getColumn(5).setPreferredWidth(30);
                //TablGest.getTableHeader().setDefaultRenderer(new header);
    }
    public void ChgeCntAcess_FcTxtBrcd(){
    jTextField1.requestFocus();
   // jLabel3.setText(takeRepastRemplissage.NBResident(TimeRepat)+"");
     this.getInputContext().selectInputMethod(new Locale("fr", "FR"));
     
       Toolkit.getDefaultToolkit().setLockingKeyState(KeyEvent.VK_CAPS_LOCK, true);
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        PanTabStd = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablStd = new javax.swing.JTable(){

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;

            }};
            jPanel5 = new javax.swing.JPanel();
            jLabel48 = new javax.swing.JLabel();
            NumCardG = new javax.swing.JLabel();
            Nam_StdG = new javax.swing.JLabel();
            SurNam_Std_G = new javax.swing.JLabel();
            jLabel47 = new javax.swing.JLabel();
            jLabel49 = new javax.swing.JLabel();
            IDResidentG = new javax.swing.JLabel();
            jLabel54 = new javax.swing.JLabel();
            jTextField10 = new javax.swing.JTextField();
            jLabel55 = new javax.swing.JLabel();
            jLabel43 = new javax.swing.JLabel();
            jTextField9 = new javax.swing.JTextField();
            jTextField12 = new javax.swing.JTextField();
            jLabel56 = new javax.swing.JLabel();
            jLabel57 = new javax.swing.JLabel();
            jTextField11 = new javax.swing.JTextField();
            PanTabGuest = new javax.swing.JPanel();
            jScrollPane5 = new javax.swing.JScrollPane();
            TablGest = new javax.swing.JTable(){
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;

                }
                @Override
                public Component prepareRenderer (TableCellRenderer renderer, int rowIndex, int columnIndex){
                    Component componenet = super.prepareRenderer(renderer, rowIndex, columnIndex);

                    Object value = getModel().getValueAt(rowIndex,columnIndex);

                    if(columnIndex == 0){

                        if(value.equals("مستضيف"))
                        {

                            componenet.setBackground(Color.GREEN);
                            componenet.setForeground(Color.BLACK);

                        }
                        if(value.equals("نهاية الاستضافة")){
                            // if date  equal current date
                            componenet.setBackground(new Color(0,204,255));
                            componenet.setForeground(Color.BLACK);
                        }

                        if(value.equals("مقبول")){
                            // if date  equal current date
                            componenet.setBackground(Color.YELLOW);
                            componenet.setForeground(Color.BLACK);
                        }

                        if(value.equals("غير مقبول")){
                            // if date  equal current date
                            componenet.setBackground(Color.RED);
                            componenet.setForeground(Color.WHITE);
                        }

                    }
                    return componenet;
                }

            };
            jTextField8 = new javax.swing.JTextField();
            jTextField7 = new javax.swing.JTextField();
            jTextField6 = new javax.swing.JTextField();
            jTextField5 = new javax.swing.JTextField();
            jLabel39 = new javax.swing.JLabel();
            jLabel40 = new javax.swing.JLabel();
            jLabel42 = new javax.swing.JLabel();
            jLabel41 = new javax.swing.JLabel();
            jLabel12 = new javax.swing.JLabel();
            jLabel161 = new javax.swing.JLabel();
            LabGuest = new javax.swing.JLabel();
            BtnSaveStd8 = new javax.swing.JButton();
            BtnSaveStd7 = new javax.swing.JButton();
            jPanel3 = new javax.swing.JPanel();
            PanReception = new javax.swing.JPanel();
            jLabel3 = new javax.swing.JLabel();
            jTextField1 = new javax.swing.JTextField();
            jLabel51 = new javax.swing.JLabel();
            jLabel104 = new javax.swing.JLabel();
            jLabel101 = new javax.swing.JLabel();
            jLabel52 = new javax.swing.JLabel();
            jLabel53 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            jLabel8 = new javax.swing.JLabel();
            jLabel9 = new javax.swing.JLabel();
            LabPrfBranch_Std = new javax.swing.JLabel();
            jLabel10 = new javax.swing.JLabel();
            jLabel11 = new javax.swing.JLabel();
            jLabel17 = new javax.swing.JLabel();
            PanGuests = new javax.swing.JPanel();
            DatInscrpInUniv = new javax.swing.JFormattedTextField();
            jLabel182 = new javax.swing.JLabel();
            NbrDays = new javax.swing.JTextField();
            txtPlcBirth_Prof3 = new javax.swing.JTextField();
            jLabel157 = new javax.swing.JLabel();
            txtNam_Prof2 = new javax.swing.JTextField();
            txtSurNam_Prof2 = new javax.swing.JTextField();
            jLabel100 = new javax.swing.JLabel();
            jLabel103 = new javax.swing.JLabel();
            jLabel50 = new javax.swing.JLabel();
            NumCardGues = new javax.swing.JTextField();
            jLabel14 = new javax.swing.JLabel();
            NumBac = new javax.swing.JTextField();
            jLabel126 = new javax.swing.JLabel();
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel13 = new javax.swing.JLabel();
            jLabel15 = new javax.swing.JLabel();
            jLabel20 = new javax.swing.JLabel();
            jLabel16 = new javax.swing.JLabel();
            jButton5 = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setBackground(new java.awt.Color(0, 204, 204));
            setUndecorated(true);
            setResizable(false);
            addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowOpened(java.awt.event.WindowEvent evt) {
                    formWindowOpened(evt);
                }
            });
            getContentPane().setLayout(new java.awt.CardLayout());

            jPanel2.setBackground(new java.awt.Color(255, 255, 255));
            jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
            jPanel2.setMinimumSize(new java.awt.Dimension(1116, 500));
            jPanel2.setPreferredSize(new java.awt.Dimension(960, 710));
            jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                public void mouseDragged(java.awt.event.MouseEvent evt) {
                    jPanel2MouseDragged(evt);
                }
            });
            jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    jPanel2MousePressed(evt);
                }
                public void mouseReleased(java.awt.event.MouseEvent evt) {
                    jPanel2MouseReleased(evt);
                }
            });
            jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jPanel1.setLayout(new java.awt.CardLayout());

            PanTabStd.setBackground(new java.awt.Color(0, 190, 190));
            PanTabStd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            TablStd.getTableHeader().setReorderingAllowed(false);
            TablStd.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "مـكان الــميلاد", "تـاريـخ الــمـيلاد", "الـلقب", "الاســم", "رقـم البـطاقة", "ID"
                }
            ));
            TablStd.setRowHeight(25);
            TablStd.setSelectionBackground(new java.awt.Color(0, 153, 0));
            TablStd.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    TablStdMouseClicked(evt);
                }
            });
            jScrollPane3.setViewportView(TablStd);

            PanTabStd.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 500, 290));

            jPanel5.setBackground(new java.awt.Color(0, 190, 190));
            jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel48.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel48.setText("رقــم الـــبــطــاقــة         :");
            jLabel48.setToolTipText("");
            jLabel48.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
            jPanel5.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 130, 27));

            NumCardG.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
            NumCardG.setForeground(new java.awt.Color(255, 51, 51));
            NumCardG.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
            jPanel5.add(NumCardG, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 70, 20));

            Nam_StdG.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
            Nam_StdG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            Nam_StdG.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
            jPanel5.add(Nam_StdG, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 100, 30));

            SurNam_Std_G.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
            SurNam_Std_G.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            SurNam_Std_G.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
            jPanel5.add(SurNam_Std_G, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 90, 30));

            jLabel47.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel47.setText("لــقــب الـــمــسـتــضيـف  :");
            jLabel47.setToolTipText("SurNam");
            jLabel47.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
            jPanel5.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 130, 27));

            jLabel49.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel49.setText("اســـم الـــمــسـتــضيـف  :");
            jLabel49.setToolTipText("");
            jLabel49.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
            jPanel5.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 130, 30));

            IDResidentG.setForeground(new java.awt.Color(0, 190, 190));
            jPanel5.add(IDResidentG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 70, 30));

            PanTabStd.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 480, 90));

            jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residence/Image/clean.png"))); // NOI18N
            jLabel54.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            jLabel54.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel54MouseClicked(evt);
                }
            });
            PanTabStd.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

            jTextField10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jTextField10.setForeground(java.awt.Color.blue);
            jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    jTextField10KeyReleased(evt);
                }
            });
            PanTabStd.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 90, 25));

            jLabel55.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel55.setForeground(new java.awt.Color(255, 255, 255));
            jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel55.setText("تاريخ الميلاد");
            PanTabStd.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 80, 20));

            jLabel43.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel43.setForeground(new java.awt.Color(255, 255, 255));
            jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel43.setText("الـلـقـــب ");
            PanTabStd.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 50, 20));

            jTextField9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jTextField9.setForeground(java.awt.Color.blue);
            jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    jTextField9KeyReleased(evt);
                }
            });
            PanTabStd.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 90, 25));

            jTextField12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jTextField12.setForeground(java.awt.Color.blue);
            jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    jTextField12KeyReleased(evt);
                }
            });
            PanTabStd.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 90, 25));

            jLabel56.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel56.setForeground(new java.awt.Color(255, 255, 255));
            jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel56.setText("الاســم ");
            PanTabStd.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 50, 20));

            jLabel57.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel57.setForeground(new java.awt.Color(255, 255, 255));
            jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel57.setText("رقم البطـاقة");
            PanTabStd.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 70, 20));

            jTextField11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jTextField11.setForeground(new java.awt.Color(255, 0, 51));
            jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    jTextField11KeyReleased(evt);
                }
            });
            PanTabStd.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 70, 25));

            jPanel1.add(PanTabStd, "card3");

            PanTabGuest.setBackground(new java.awt.Color(0, 190, 190));
            PanTabGuest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            TablGest.getTableHeader().setReorderingAllowed(false);
            TablGest.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
            TablGest.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "الموافقة", "نهاية الاستضافة", " الايام", "تاريخ الاستضافة", "رقم التسجيل", "اللقب ", "الاسم", "N °", "ID"
                }
            ));
            TablGest.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
            TablGest.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            TablGest.setRowHeight(25);
            TablGest.setSelectionBackground(new java.awt.Color(51, 153, 0));
            TablGest.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    TablGestMouseClicked(evt);
                }
            });
            jScrollPane5.setViewportView(TablGest);

            PanTabGuest.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 500, 280));

            jTextField8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jTextField8.setForeground(java.awt.Color.blue);
            jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            jTextField8.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField8ActionPerformed(evt);
                }
            });
            jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    jTextField8KeyReleased(evt);
                }
            });
            PanTabGuest.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 80, 25));

            jTextField7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jTextField7.setForeground(java.awt.Color.blue);
            jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            jTextField7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField7ActionPerformed(evt);
                }
            });
            jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    jTextField7KeyReleased(evt);
                }
            });
            PanTabGuest.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 80, 25));

            jTextField6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jTextField6.setForeground(java.awt.Color.blue);
            jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    jTextField6KeyReleased(evt);
                }
            });
            PanTabGuest.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 80, 25));

            jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jTextField5.setForeground(new java.awt.Color(255, 0, 51));
            jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    jTextField5KeyReleased(evt);
                }
            });
            PanTabGuest.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 90, 25));

            jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel39.setForeground(new java.awt.Color(255, 255, 255));
            jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel39.setText("رقم البطـاقة");
            PanTabGuest.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 70, 20));

            jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel40.setForeground(new java.awt.Color(255, 255, 255));
            jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel40.setText("الاســم ");
            PanTabGuest.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 50, 20));

            jLabel42.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel42.setForeground(new java.awt.Color(255, 255, 255));
            jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel42.setText("الـلـقـــب ");
            PanTabGuest.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 50, 20));

            jLabel41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel41.setForeground(new java.awt.Color(255, 255, 255));
            jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel41.setText("تاريخ الميلاد");
            PanTabGuest.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 80, 20));

            jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residence/Image/clean.png"))); // NOI18N
            jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel12MouseClicked(evt);
                }
            });
            PanTabGuest.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

            jPanel1.add(PanTabGuest, "card2");

            jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 520, 440));

            jLabel161.setBackground(new java.awt.Color(0, 190, 190));
            jLabel161.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel161.setForeground(new java.awt.Color(255, 255, 255));
            jLabel161.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel161.setText(" الــطــلـــبـة");
            jLabel161.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            jLabel161.setOpaque(true);
            jLabel161.setPreferredSize(new java.awt.Dimension(70, 17));
            jLabel161.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel161MouseClicked(evt);
                }
            });
            jPanel2.add(jLabel161, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 160, 40));

            LabGuest.setBackground(new java.awt.Color(0, 153, 153));
            LabGuest.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
            LabGuest.setForeground(new java.awt.Color(255, 255, 255));
            LabGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            LabGuest.setText(" الــضــيـــوف");
            LabGuest.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            LabGuest.setOpaque(true);
            LabGuest.setPreferredSize(new java.awt.Dimension(70, 17));
            LabGuest.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    LabGuestMouseClicked(evt);
                }
            });
            jPanel2.add(LabGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 160, 40));

            BtnSaveStd8.setBackground(new java.awt.Color(51, 204, 0));
            BtnSaveStd8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
            BtnSaveStd8.setForeground(new java.awt.Color(255, 255, 255));
            BtnSaveStd8.setText("حــفــظ");
            BtnSaveStd8.setToolTipText("");
            BtnSaveStd8.setContentAreaFilled(false);
            BtnSaveStd8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            BtnSaveStd8.setDefaultCapable(false);
            BtnSaveStd8.setOpaque(true);
            BtnSaveStd8.setPreferredSize(new java.awt.Dimension(57, 36));
            BtnSaveStd8.setSelected(true);
            BtnSaveStd8.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BtnSaveStd8ActionPerformed(evt);
                }
            });
            jPanel2.add(BtnSaveStd8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, 110, 40));

            BtnSaveStd7.setBackground(new java.awt.Color(51, 204, 0));
            BtnSaveStd7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
            BtnSaveStd7.setForeground(new java.awt.Color(255, 255, 255));
            BtnSaveStd7.setText("الــغــاء");
            BtnSaveStd7.setToolTipText("");
            BtnSaveStd7.setContentAreaFilled(false);
            BtnSaveStd7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            BtnSaveStd7.setDefaultCapable(false);
            BtnSaveStd7.setOpaque(true);
            BtnSaveStd7.setPreferredSize(new java.awt.Dimension(57, 36));
            BtnSaveStd7.setSelected(true);
            BtnSaveStd7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BtnSaveStd7ActionPerformed(evt);
                }
            });
            jPanel2.add(BtnSaveStd7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 110, 40));

            jPanel3.setBackground(new java.awt.Color(255, 255, 255));
            jPanel3.setLayout(new java.awt.CardLayout());

            PanReception.setBackground(new java.awt.Color(255, 255, 255));
            PanReception.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
            PanReception.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 120));

            jTextField1.setBackground(new java.awt.Color(255, 255, 204));
            jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
            jTextField1.setForeground(new java.awt.Color(255, 0, 51));
            jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
            jTextField1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField1ActionPerformed(evt);
                }
            });
            PanReception.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 380, 50));

            jLabel51.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
            jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel51.setText("مـــعــــلـــــومــــات الـــمـــقـــيـــم");
            jLabel51.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
            PanReception.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 260, 30));

            jLabel104.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
            jLabel104.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel104.setText("الاســـــــم                : ");
            jLabel104.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
            PanReception.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 100, 30));

            jLabel101.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
            jLabel101.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel101.setText("الــلـــقــــب             : ");
            jLabel101.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
            PanReception.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 100, 30));

            jLabel52.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel52.setText("تـاريـخ الــمـيـلاد    :");
            jLabel52.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
            PanReception.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 100, 30));

            jLabel53.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel53.setText("رقـــم الــبــطــاقـة   :");
            jLabel53.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
            PanReception.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 100, 30));

            jLabel4.setBackground(new java.awt.Color(255, 255, 204));
            jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(255, 0, 51));
            jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
            jLabel4.setOpaque(true);
            PanReception.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 140, 30));

            jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
            jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel5.setText("بــ");
            PanReception.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 20, 30));

            jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel6.setForeground(java.awt.Color.blue);
            jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel6.setToolTipText("");
            PanReception.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 110, 30));

            jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel7.setForeground(java.awt.Color.blue);
            jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel7.setToolTipText("");
            PanReception.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 110, 30));

            jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel8.setForeground(java.awt.Color.blue);
            jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            PanReception.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 100, 30));

            jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel9.setForeground(java.awt.Color.blue);
            jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel9.setToolTipText("");
            PanReception.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 80, 30));

            LabPrfBranch_Std.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            LabPrfBranch_Std.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            LabPrfBranch_Std.setText("الـــشــعــبــة         :");
            LabPrfBranch_Std.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
            PanReception.add(LabPrfBranch_Std, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 100, 30));

            jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel10.setForeground(java.awt.Color.blue);
            jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            PanReception.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 160, 30));

            jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
            jLabel11.setForeground(new java.awt.Color(255, 0, 51));
            jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            PanReception.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 190, 40));

            jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
            jLabel17.setForeground(new java.awt.Color(0, 102, 255));
            jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel17.setText("الوضعيــــــــة");
            PanReception.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 150, 40));

            jPanel3.add(PanReception, "card3");

            PanGuests.setBackground(new java.awt.Color(255, 255, 255));
            PanGuests.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            DatInscrpInUniv.setForeground(java.awt.Color.blue);
            try {
                DatInscrpInUniv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
            } catch (java.text.ParseException ex) {
                ex.printStackTrace();
            }
            DatInscrpInUniv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            DatInscrpInUniv.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
            SimpleDateFormat formatDat=new SimpleDateFormat("dd/MM/YYYY");
            String DatInscrpStr=formatDat.format(new Date());

            DatInscrpInUniv.setText(DatInscrpStr);
            PanGuests.add(DatInscrpInUniv, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 170, 30));

            jLabel182.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
            jLabel182.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel182.setText("عـدد الايام الاسـتـضـافـة :");
            jLabel182.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
            PanGuests.add(jLabel182, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, 34));

            NbrDays.setBackground(new java.awt.Color(255, 255, 204));
            NbrDays.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            NbrDays.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            NbrDays.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    NbrDaysFocusGained(evt);
                }
            });
            NbrDays.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    NbrDaysKeyTyped(evt);
                }
            });
            PanGuests.add(NbrDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 120, 34));

            txtPlcBirth_Prof3.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
            txtPlcBirth_Prof3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtPlcBirth_Prof3.setText("يــــوم");
            txtPlcBirth_Prof3.setBorder(null);
            txtPlcBirth_Prof3.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    txtPlcBirth_Prof3FocusGained(evt);
                }
            });
            txtPlcBirth_Prof3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtPlcBirth_Prof3ActionPerformed(evt);
                }
            });
            txtPlcBirth_Prof3.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    txtPlcBirth_Prof3KeyPressed(evt);
                }
            });
            PanGuests.add(txtPlcBirth_Prof3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 40, 34));

            jLabel157.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
            jLabel157.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel157.setText("تـاريـخ الاسـتـضـافـة :");
            jLabel157.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
            PanGuests.add(jLabel157, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 110, 34));

            txtNam_Prof2.setBackground(new java.awt.Color(255, 255, 204));
            txtNam_Prof2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            txtNam_Prof2.setForeground(new java.awt.Color(153, 153, 153));
            txtNam_Prof2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtNam_Prof2.setText("ادخل الاسم");
            txtNam_Prof2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            txtNam_Prof2.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    txtNam_Prof2FocusGained(evt);
                }
            });
            txtNam_Prof2.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    txtNam_Prof2KeyPressed(evt);
                }
            });
            PanGuests.add(txtNam_Prof2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 165, 34));

            txtSurNam_Prof2.setBackground(new java.awt.Color(255, 255, 204));
            txtSurNam_Prof2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            txtSurNam_Prof2.setForeground(new java.awt.Color(153, 153, 153));
            txtSurNam_Prof2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtSurNam_Prof2.setText("ادخل اللقب");
            txtSurNam_Prof2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            txtSurNam_Prof2.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    txtSurNam_Prof2FocusGained(evt);
                }
            });
            txtSurNam_Prof2.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    txtSurNam_Prof2KeyPressed(evt);
                }
            });
            PanGuests.add(txtSurNam_Prof2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 165, 34));

            jLabel100.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
            jLabel100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel100.setText("الــلـــقــــب             : ");
            jLabel100.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
            PanGuests.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 100, 34));

            jLabel103.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
            jLabel103.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel103.setText("الاســـــــم                : ");
            jLabel103.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
            PanGuests.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 100, 34));

            jLabel50.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel50.setText("رقـــم الــبــطــاقـة   :");
            jLabel50.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
            PanGuests.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 100, 34));

            NumCardGues.setBackground(new java.awt.Color(255, 255, 204));
            NumCardGues.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
            NumCardGues.setForeground(new java.awt.Color(255, 51, 51));
            NumCardGues.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            NumCardGues.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
            NumCardGues.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    NumCardGuesActionPerformed(evt);
                }
            });
            NumCardGues.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    NumCardGuesKeyPressed(evt);
                }
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    NumCardGuesKeyTyped(evt);
                }
            });
            PanGuests.add(NumCardGues, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 160, 34));

            jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
            jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel14.setText("مــــعــــلـــومـــات الـــــضـــيــف");
            jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
            jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel14MouseClicked(evt);
                }
            });
            PanGuests.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 290, 34));

            NumBac.setBackground(new java.awt.Color(255, 255, 204));
            NumBac.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            NumBac.setForeground(new java.awt.Color(153, 153, 153));
            NumBac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            NumBac.setText("رقــم الـتـسـجــيــل");
            NumBac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            NumBac.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    NumBacFocusGained(evt);
                }
            });
            NumBac.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    NumBacActionPerformed(evt);
                }
            });
            NumBac.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    NumBacKeyPressed(evt);
                }
            });
            PanGuests.add(NumBac, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 165, 34));

            jLabel126.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
            jLabel126.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            jLabel126.setText("رقــم الـتـسـجــيــل   :");
            jLabel126.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
            PanGuests.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 100, 34));

            jPanel3.add(PanGuests, "card2");

            jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 400, 420));

            jLabel1.setBackground(new java.awt.Color(0, 153, 153));
            jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(255, 255, 255));
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("خــــدمـــة الــضــيـــوف");
            jLabel1.setToolTipText("");
            jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            jLabel1.setOpaque(true);
            jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel1MouseClicked(evt);
                }
            });
            jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 130, 40));

            jLabel2.setBackground(new java.awt.Color(0, 190, 190));
            jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(255, 255, 255));
            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel2.setText("خـــدمــة الـــدخـــول");
            jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            jLabel2.setOpaque(true);
            jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel2MouseClicked(evt);
                }
            });
            jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 140, 40));

            jLabel13.setBackground(new java.awt.Color(0, 153, 153));
            jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel13.setForeground(new java.awt.Color(255, 255, 255));
            jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel13.setText("مـــغـــادرة الـضـيف");
            jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            jLabel13.setOpaque(true);
            jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel13MouseClicked(evt);
                }
            });
            jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, 120, 40));

            jLabel15.setForeground(new java.awt.Color(255, 255, 255));
            jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 110, 20));

            jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residence/Image/iconsCls.png"))); // NOI18N
            jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel20MouseClicked(evt);
                }
            });
            jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 30, -1));

            jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residence/Image/Minize.png"))); // NOI18N
            jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel16MouseClicked(evt);
                }
            });
            jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 30, 25));

            jButton5.setBackground(new java.awt.Color(255, 255, 255));
            jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jButton5.setText("تحميل المعطيات");
            jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jButton5.setContentAreaFilled(false);
            jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            jButton5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton5ActionPerformed(evt);
                }
            });
            jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 90, 40));

            getContentPane().add(jPanel2, "card3");

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void TablGestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablGestMouseClicked
      int row = (int) TablGest.getSelectedRow();
    /*    Resident_GlRemplissage.Get_Std_Of_Guest(ID_Resident, NumCardG, Nam_StdG, SurNam_Std_G);*/
    jLabel15.setText((int)TablGest.getValueAt(row, 7)+"");
    }//GEN-LAST:event_TablGestMouseClicked

    private void jLabel161MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel161MouseClicked
       // JOptionPane.showMessageDialog(null, "..................................................................");

       PanTabStd.setVisible(true); 
       PanTabGuest.setVisible(false);
        
        Resident_GlRemplissage.DisplayAllResidentInTableGuest(TablStd);
        NumCardG.setText("");
        Nam_StdG.setText("");
        SurNam_Std_G.setText("");
        IDResidentG.setText("");
        jLabel161.setBackground(new Color(0, 190, 190));
        LabGuest.setBackground(new Color(0, 153, 153));
        
    }//GEN-LAST:event_jLabel161MouseClicked

    private void LabGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabGuestMouseClicked
        PanTabStd.setVisible(false);
        PanTabGuest.setVisible(true);
        NumCardG.setText("");
        Nam_StdG.setText("");
        SurNam_Std_G.setText("");
        LabGuest.setBackground(new Color(0, 190, 190));
        jLabel161.setBackground(new Color(0, 153, 153));
        guestRmpissage.DisplayTableGuests(TablGest);
        //ChangeSigneRow();
        
    }//GEN-LAST:event_LabGuestMouseClicked

    private void TablStdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablStdMouseClicked
        int Row = TablStd.getSelectedRow();
        IDResidentG.setText((int) TablStd.getValueAt(Row, 5) + "");
        NumCardG.setText((int) TablStd.getValueAt(Row, 4) + "");
        Nam_StdG.setText((String) TablStd.getValueAt(Row, 3));
        SurNam_Std_G.setText((String) TablStd.getValueAt(Row, 2));
    }//GEN-LAST:event_TablStdMouseClicked

    private void BtnSaveStd8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveStd8ActionPerformed
        if (!NumCardG.getText().equals("") && !txtNam_Prof2.getText().equals("") && !txtNam_Prof2.getText().equals("ادخل الاسم")
                && !txtNam_Prof2.equals("") && !txtNam_Prof2.getText().equals("ادخل اللقب") && !NbrDays.getText().equals("")) {
                 int NumCard=0;
                 
            // NumCard=Integer.parseInt(NumCardGues.getText());
             if (NumCardGues.getText().equals("")) {
                 
            }else
             {
             NumCard=Integer.parseInt(NumCardGues.getText());             
             }
            int ID =Integer.parseInt(IDResidentG.getText());
                SimpleDateFormat f=new SimpleDateFormat("dd/MM/YYYY");
                int nb=Integer.parseInt(NbrDays.getText());
            Date t=null;
                try {
                 t=guestRmpissage.GetDate_Hosting(nb);
            } catch (ParseException ex) {
                Logger.getLogger(Guest1.class.getName()).log(Level.SEVERE, null, ex);
            }
                guest = new Guest(txtNam_Prof2.getText(), txtSurNam_Prof2.getText(),NumCard,
                        new Date(),nb,t,NumBac.getText() ,ID);
                guest.AddGuest();
             //   JOptionPane.showMessageDialog(null," "+NumCard);
               // guest.UpdateGuets(NumCard);   // here update after connect to Server 
                InitailisationGuestPan();
                ok=new Ok1(this,true, "لــقــد تــم الحفظ بنجاح");
           ok.setVisible(true);
            
           
        } else if (NumCardG.getText().equals("") && (txtNam_Prof2.getText().equals("") || txtNam_Prof2.getText().equals("ادخل الاسم")
                || txtNam_Prof2.equals("") || txtNam_Prof2.getText().equals("ادخل اللقب") || NbrDays.getText().equals(""))) {

            messagerror = new MessageErrorControl(this, true, "الــرجــاءادخــال مـعــلومــات الـضـيف و اخــتــيــار الــطــالــب الــمــضـيـف  مـن الـجــدول");
            messagerror.setVisible(true);
        } else if (NumCardG.getText().equals("")) {
            messagerror = new MessageErrorControl(this, true, " الــرجــاء اخــتــيــار الــطــالــب الــمــضـيـف مـن الـجــدول");
            messagerror.setVisible(true);
        } else {
            messagerror = new MessageErrorControl(this, true, "  الــرجــاء ادخــال  مـعــلومــات الــضـــيــف كــاملـة");
            messagerror.setVisible(true);
        }
    }//GEN-LAST:event_BtnSaveStd8ActionPerformed

    private void BtnSaveStd7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveStd7ActionPerformed
           InitailisationGuestPan();
    }//GEN-LAST:event_BtnSaveStd7ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        jLabel11.setText("");
        int Id_Resident=0;
        String a = jTextField1.getText();
        String Cod;
      
        if (a.startsWith("0251") || a.startsWith("251")) {
            if (a.startsWith("0")) {
                Cod = a.substring(1);
            } else {
                Cod = a;
            }

            int P = Resident_GlRemplissage.GetIformationCard(Cod, jLabel4, jLabel6, jLabel7, jLabel9, jLabel8, jLabel10, jLabel3,jLabel11);
            
            if (P == 1 || P == 3) {
                jLabel51.setText("مـــعــــلـــــومــــات الـــمـــقـــيـــم");
                LabPrfBranch_Std.setText("الـــشــعــبــة         :");
            }
            if (P == 2) {
              
                jLabel51.setText("مـــعــــلـــــومــــات الـــطـــالـــب");
                LabPrfBranch_Std.setText("الـــشــعــبــة         :");
            }
            if (P == 4) {
                jLabel51.setText("مـــعــــلـــــومــــات الـــعــامــــل");
                LabPrfBranch_Std.setText("الــمــهــنـــــة        :");
            }
            if (P == 0) {
                jLabel11.setText(" خــــارجــــي ؟؟؟؟؟؟؟؟؟");
                jLabel4.setText("");
                jLabel6.setText("");
                jLabel7.setText("");
                jLabel9.setText("");
                jLabel8.setText("");
                jLabel10.setText("");
                File ImageResidentToSv = new File("D:\\Image_Signature\\imageRes.png");
                ImageIcon imgeicon = new ImageIcon(new ImageIcon(ImageResidentToSv.getAbsolutePath()).getImage().getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH));
                jLabel3.setIcon(imgeicon);
//        jLabel3.setIcon((Icon) new ImageIcon(getClass().getResource("/residence/Image/imageRes.png")).getImage().getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH));

            }

        } else {
            jLabel4.setText("");
            jLabel6.setText("");
            jLabel7.setText("");
            jLabel9.setText("");
            jLabel8.setText("");
            jLabel10.setText("");
            jLabel3.setText("");
            jLabel11.setText(" خــــارجــــي ؟؟؟؟؟؟؟؟؟");
            File ImageResidentToSv = new File("D:\\Image_Signature\\imageRes.png");
            ImageIcon imgeicon = new ImageIcon(new ImageIcon(ImageResidentToSv.getAbsolutePath()).getImage().getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH));
            jLabel3.setIcon(imgeicon);
            //   jLabel3.setIcon((Icon) new ImageIcon(getClass().getResource("/residence/Image/imageRes.png")).getImage().getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH));
        }

        //  jLabel26.setText("");
        /* if(jTextField1.getText().startsWith("0")){
            int numCard=Integer.parseInt(jTextField1.getText().substring(4));

            jLabel4.setText(""+numCard);
            
            int P=Resident_GlRemplissage.GetIformationCard(numCard,jLabel6,jLabel7,jLabel9,jLabel8,jLabel10);
            if(P==1 || P==3){jLabel51.setText("مـــعــــلـــــومــــات الـــمـــقـــيـــم");
                LabPrfBranch_Std.setText("الـــشــعــبــة         :");}
            if(P==2){{jLabel51.setText("مـــعــــلـــــومــــات الـــطـــالـــب");}
                LabPrfBranch_Std.setText("الـــشــعــبــة         :");}
            if(P==4){jLabel51.setText("مـــعــــلـــــومــــات الـــعــامــــل");
                LabPrfBranch_Std.setText("الــمــهــنـــــة        :");}
            if(P==0){jLabel11.setText("غـــــيـتــر مـــقــيـــــم");}
          
        }*/
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        LabGuest.setVisible(false);
        PanGuests.setVisible(false);
        PanTabStd.setVisible(true);
        PanReception.setVisible(true);
        jPanel5.setVisible(false);
        BtnSaveStd7.setVisible(false);
        BtnSaveStd8.setVisible(false);
        jLabel161.setBackground(new Color(0, 190, 190));
        LabGuest.setBackground(new Color(0, 153, 153));
        jLabel2.setBackground(new Color(0, 190, 190));
        jLabel1.setBackground(new Color(0, 153, 153));
        ChgeCntAcess_FcTxtBrcd();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       PanReception.setVisible(false);
        LabGuest.setVisible(true);
       
        PanGuests.setVisible(true);
        PanTabStd.setVisible(false);
        jPanel5.setVisible(true);
        BtnSaveStd8.setVisible(true);
        BtnSaveStd7.setVisible(true);
        LabGuest.setBackground(new Color(0, 153, 153));
        jLabel161.setBackground(new Color(0, 190, 190));
        jLabel1.setBackground(new Color(0, 190, 190));
        jLabel2.setBackground(new Color(0, 153, 153));
        InitailisationGuestPan();
    }//GEN-LAST:event_jLabel1MouseClicked
DefaultTableModel d;
Ok1 ok;
    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
       if(TablGest.getSelectedRow() !=-1){
          int Numcard= Integer.parseInt(jLabel15.getText());
           guestRmpissage.UpdateGuets2(Numcard);
           TablGest.getSelectionModel().clearSelection();
           jLabel15.setText("");
           ok=new Ok1(this,true, "لــقــد تــم حـــذف الــضــيـف من قائمة الاطعام");
           ok.setVisible(true);
       }else{
        messagerror=new  MessageErrorControl(this, true, "الــرجـــاء اخــتــيار الــضـيـف ثــم الـضـغـط ");
        messagerror.setVisible(true);
       }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel54MouseClicked
        Fill_Data.CleanTextFld(jTextField9,jTextField10,jTextField11,jTextField12);
        Fill_Data.FilterResidentMlt(jTextField9,jTextField10,jTextField11,jTextField12,TablStd,(DefaultTableModel) TablStd.getModel());  //filtrer dans le tableau fournisseur
        NumCardG.setText("");
        Nam_StdG.setText("");
        SurNam_Std_G.setText("");
        IDResidentG.setText("");
    }//GEN-LAST:event_jLabel54MouseClicked

    private void jTextField10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyReleased
        Fill_Data.FilterResidentMlt(jTextField9,jTextField10,jTextField11,jTextField12,TablStd,(DefaultTableModel) TablStd.getModel());  //filtrer dans le tableau fournisseur
    }//GEN-LAST:event_jTextField10KeyReleased

    private void jTextField9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyReleased
        Fill_Data.FilterResidentMlt(jTextField9,jTextField10,jTextField11,jTextField12,TablStd,(DefaultTableModel) TablStd.getModel());  //filtrer dans le tableau fournisseur
    }//GEN-LAST:event_jTextField9KeyReleased

    private void jTextField12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyReleased
        Fill_Data.FilterResidentMlt(jTextField9,jTextField10,jTextField11,jTextField12,TablStd,(DefaultTableModel) TablStd.getModel());  //filtrer dans le tableau fournisseur
    }//GEN-LAST:event_jTextField12KeyReleased

    private void jTextField11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyReleased
        Fill_Data.FilterResidentMlt(jTextField9,jTextField10,jTextField11,jTextField12,TablStd,(DefaultTableModel) TablStd.getModel());  //filtrer dans le tableau fournisseur
    }//GEN-LAST:event_jTextField11KeyReleased

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        Fill_Data.FilterResidentMlt(jTextField5,jTextField6,jTextField7,jTextField8,TablGest,(DefaultTableModel) TablGest.getModel());  //filtrer dans le tableau fournisseur
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased
        Fill_Data.FilterResidentMlt(jTextField5,jTextField6,jTextField7,jTextField8,TablGest,(DefaultTableModel) TablGest.getModel());  //filtrer dans le tableau fournisseur
    }//GEN-LAST:event_jTextField7KeyReleased

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        Fill_Data.FilterResidentMlt(jTextField5,jTextField6,jTextField7,jTextField8,TablGest,(DefaultTableModel) TablGest.getModel());  //filtrer dans le tableau fournisseur
    }//GEN-LAST:event_jTextField6KeyReleased

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        Fill_Data.FilterResidentMlt(jTextField5,jTextField6,jTextField7,jTextField8,TablGest,(DefaultTableModel) TablGest.getModel());  //filtrer dans le tableau fournisseur
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        Fill_Data.CleanTextFld(jTextField5, jTextField6, jTextField7, jTextField8);
        Fill_Data.FilterResidentMlt(jTextField5,jTextField6,jTextField7,jTextField8,TablGest,(DefaultTableModel) TablGest.getModel());  //filtrer dans le tableau fournisseur
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void NumBacKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumBacKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtNam_Prof2.requestFocus();
        }
    }//GEN-LAST:event_NumBacKeyPressed

    private void NumBacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumBacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumBacActionPerformed

    private void NumBacFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NumBacFocusGained
        if (NumBac.getText().equals("رقــم الـتـسـجــيــل")) {
            NumBac.setText("");
        }
        NumBac.setForeground(Color.blue);
    }//GEN-LAST:event_NumBacFocusGained

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked

    }//GEN-LAST:event_jLabel14MouseClicked

    private void NumCardGuesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumCardGuesKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_BACK_SPACE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_NumCardGuesKeyTyped

    private void NumCardGuesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumCardGuesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            NumBac.requestFocus();
        }
    }//GEN-LAST:event_NumCardGuesKeyPressed

    private void NumCardGuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumCardGuesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumCardGuesActionPerformed

    private void txtSurNam_Prof2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSurNam_Prof2FocusGained

        if (txtSurNam_Prof2.getText().equals("ادخل اللقب")) {
            txtSurNam_Prof2.setText("");
        }
        txtSurNam_Prof2.setForeground(Color.blue);
    }//GEN-LAST:event_txtSurNam_Prof2FocusGained

    private void txtNam_Prof2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNam_Prof2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtSurNam_Prof2.requestFocus();
        }
    }//GEN-LAST:event_txtNam_Prof2KeyPressed

    private void txtNam_Prof2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNam_Prof2FocusGained
        if (txtNam_Prof2.getText().equals("ادخل الاسم")) {
            txtNam_Prof2.setText("");
        }
        txtNam_Prof2.setForeground(Color.blue);
    }//GEN-LAST:event_txtNam_Prof2FocusGained

    private void txtPlcBirth_Prof3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlcBirth_Prof3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlcBirth_Prof3KeyPressed

    private void txtPlcBirth_Prof3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlcBirth_Prof3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlcBirth_Prof3ActionPerformed

    private void txtPlcBirth_Prof3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlcBirth_Prof3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlcBirth_Prof3FocusGained

    private void NbrDaysKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NbrDaysKeyTyped

    }//GEN-LAST:event_NbrDaysKeyTyped

    private void NbrDaysFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NbrDaysFocusGained
        NbrDays.setForeground(Color.blue);
    }//GEN-LAST:event_NbrDaysFocusGained

    private void txtSurNam_Prof2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSurNam_Prof2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            NbrDays.requestFocus();
        }
    }//GEN-LAST:event_txtSurNam_Prof2KeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
ChgeCntAcess_FcTxtBrcd();
    }//GEN-LAST:event_formWindowOpened
int xx,yy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
            this.setOpacity((float) 0.7);
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased
        this.setOpacity((float) 1.0);
        
    }//GEN-LAST:event_jPanel2MouseReleased

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
         int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel16MouseClicked

    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setting.Export_Data_To_AccessDB();
    }//GEN-LAST:event_jButton5ActionPerformed
    public void InitailisationGuestPan() {
        NumCardG.setText("");
        Nam_StdG.setText("");
        SurNam_Std_G.setText("");
        NumCardG.setText("");
        Nam_StdG.setText("");
        SurNam_Std_G.setText("");
        IDResidentG.setText("");
        NumCardGues.setText("");
        txtNam_Prof2.setText("ادخل الاسم");
        txtNam_Prof2.setForeground(new Color(153, 153, 153));
        txtSurNam_Prof2.setText("ادخل اللقب");
        txtSurNam_Prof2.setForeground(new Color(153, 153, 153));
        NumBac.setText("رقــم الـتـسـجــيــل");
        NumBac.setForeground(new Color(153, 153, 153));
        NbrDays.setText("");
    }

    public  void ChangeSigneRow(){
    TablGest.setDefaultRenderer(Object.class, new DefaultTableCellRenderer(){
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column) {
            JComponent label= (JComponent) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); //To change body of generated methods, choose Tools | Templates.
        
            
            Color c=Color.red;
        int ob=(int) TablGest.getValueAt(row, 6);
        
            if (ob==20) {
                label.setBackground(c);
                TablGest.setSelectionBackground(Color.GREEN);
            }
        
        
        return  label;
        }
    
    });
    
    
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guest1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSaveStd7;
    private javax.swing.JButton BtnSaveStd8;
    private javax.swing.JFormattedTextField DatInscrpInUniv;
    private javax.swing.JLabel IDResidentG;
    private javax.swing.JLabel LabGuest;
    private javax.swing.JLabel LabPrfBranch_Std;
    private javax.swing.JLabel Nam_StdG;
    private javax.swing.JTextField NbrDays;
    private javax.swing.JTextField NumBac;
    private javax.swing.JLabel NumCardG;
    private javax.swing.JTextField NumCardGues;
    private javax.swing.JPanel PanGuests;
    private javax.swing.JPanel PanReception;
    private javax.swing.JPanel PanTabGuest;
    private javax.swing.JPanel PanTabStd;
    private javax.swing.JLabel SurNam_Std_G;
    private javax.swing.JTable TablGest;
    private javax.swing.JTable TablStd;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel182;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txtNam_Prof2;
    private javax.swing.JTextField txtPlcBirth_Prof3;
    private javax.swing.JTextField txtSurNam_Prof2;
    // End of variables declaration//GEN-END:variables
}
