/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.text.MaskFormatter;
import residence.Room;
import java.text.SimpleDateFormat;
import java.util.Date;
import residence.Conf;
import residence.TimeFormatter;

/**
 *
 * @author farid
 */
public class studentProfile extends javax.swing.JFrame {

    /**
     * Creates new form studentProfile
     */
    String SituationFam;
    int Gender;
    Room RoomRemplissage = new Room();
    Conf F ;
    String Level;
    
    public studentProfile() {
        initComponents();
        //F = new Conf(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txt_NumInsc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNam_std = new javax.swing.JTextField();
        MaskFormatter formatter3 = new TimeFormatter();
        DatBirth_std = new javax.swing.JFormattedTextField(formatter3);
        jLabel71 = new javax.swing.JLabel();
        txtSurNam_std = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        txtPlcBirth_std = new javax.swing.JTextField();
        txtNam_Father = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        txtProfission_Std = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jLabel161 = new javax.swing.JLabel();
        txtNam_mother = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        LastNamMothARTxt = new javax.swing.JTextField();
        txtProfission_Moth = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        WilayaList = new javax.swing.JComboBox<>();
        ComboxHome = new javax.swing.JComboBox<>();
        jLabel88 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        txtAddress_Std = new javax.swing.JTextField();
        jLabel81 = new javax.swing.JLabel();
        txtDairaStd = new javax.swing.JTextField();
        jLabel82 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        National_list = new javax.swing.JComboBox<>();
        jLabel67 = new javax.swing.JLabel();
        PavillonPanInf = new javax.swing.JComboBox<>();
        RomPvinPanInf = new javax.swing.JComboBox<>();
        jLabel65 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel79 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        Sti_Single1 = new javax.swing.JCheckBox();
        Std_Maried = new javax.swing.JCheckBox();
        CheckMale = new javax.swing.JCheckBox();
        checkFemal = new javax.swing.JCheckBox();
        jLabel84 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        TtxtBacYear = new javax.swing.JTextField();
        txtBacMoy = new javax.swing.JTextField();
        jLabel89 = new javax.swing.JLabel();
        txtPlaceGetBac = new javax.swing.JTextField();
        jLabel90 = new javax.swing.JLabel();
        txtBranch_std = new javax.swing.JComboBox<>();
        jLabel91 = new javax.swing.JLabel();
        DatInscrpInUniv = new javax.swing.JFormattedTextField();
        LevelStd = new javax.swing.JComboBox<>();
        jLabel87 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        txtDepa_Std = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        cLabel1 = new ViewMyPrj.CLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(761, 500));

        jPanel5.setPreferredSize(new java.awt.Dimension(852, 500));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setPreferredSize(new java.awt.Dimension(1000, 150));

        txt_NumInsc.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt_NumInsc.setForeground(new java.awt.Color(153, 153, 153));
        txt_NumInsc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_NumInsc.setText("رقــم تــسجـيــل الــبـكــالــوريــا ");
        txt_NumInsc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_NumInsc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_NumInscFocusGained(evt);
            }
        });
        txt_NumInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NumInscActionPerformed(evt);
            }
        });
        txt_NumInsc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_NumInscKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("الاســــــم");

        txtNam_std.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtNam_std.setForeground(new java.awt.Color(153, 153, 153));
        txtNam_std.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNam_std.setText("الاسم");
        txtNam_std.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNam_std.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNam_stdFocusGained(evt);
            }
        });
        txtNam_std.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNam_stdActionPerformed(evt);
            }
        });
        txtNam_std.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNam_stdKeyPressed(evt);
            }
        });

        DatBirth_std.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DatBirth_std.setForeground(new java.awt.Color(153, 153, 153));
        try {
            DatBirth_std.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        DatBirth_std.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DatBirth_std.setFont(new java.awt.Font("Times New Roman", 1,16));
        DatBirth_std.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DatBirth_stdFocusGained(evt);
            }
        });
        DatBirth_std.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DatBirth_stdKeyPressed(evt);
            }
        });

        jLabel71.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel71.setText("الـلـــقـــب");

        txtSurNam_std.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtSurNam_std.setForeground(new java.awt.Color(153, 153, 153));
        txtSurNam_std.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSurNam_std.setText("الـلـــقـــب");
        txtSurNam_std.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSurNam_std.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSurNam_stdFocusGained(evt);
            }
        });
        txtSurNam_std.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSurNam_stdKeyPressed(evt);
            }
        });

        jLabel73.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel73.setText("مــكـان الـميــلاد");

        txtPlcBirth_std.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtPlcBirth_std.setForeground(new java.awt.Color(153, 153, 153));
        txtPlcBirth_std.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPlcBirth_std.setText("مــكـان الـميــلاد");
        txtPlcBirth_std.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPlcBirth_std.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPlcBirth_stdFocusGained(evt);
            }
        });
        txtPlcBirth_std.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPlcBirth_stdKeyPressed(evt);
            }
        });

        txtNam_Father.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtNam_Father.setForeground(new java.awt.Color(153, 153, 153));
        txtNam_Father.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNam_Father.setText("اســــم الأب");
        txtNam_Father.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNam_Father.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNam_FatherFocusGained(evt);
            }
        });
        txtNam_Father.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNam_FatherKeyPressed(evt);
            }
        });

        jLabel75.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel75.setText("اســــم الأب");

        txtProfission_Std.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtProfission_Std.setForeground(new java.awt.Color(153, 153, 153));
        txtProfission_Std.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProfission_Std.setText("مهنــة الاب");
        txtProfission_Std.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtProfission_Std.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProfission_StdFocusGained(evt);
            }
        });
        txtProfission_Std.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfission_StdActionPerformed(evt);
            }
        });
        txtProfission_Std.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProfission_StdKeyPressed(evt);
            }
        });

        jLabel74.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel74.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel74.setText("مهنــة الاب ");

        jLabel161.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel161.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel161.setText(" اســم  الام");

        txtNam_mother.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtNam_mother.setForeground(new java.awt.Color(153, 153, 153));
        txtNam_mother.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNam_mother.setText("لقب  الام");
        txtNam_mother.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNam_mother.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNam_motherFocusGained(evt);
            }
        });
        txtNam_mother.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNam_motherKeyPressed(evt);
            }
        });

        jLabel76.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel76.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel76.setText("لقب  الام");

        LastNamMothARTxt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LastNamMothARTxt.setForeground(new java.awt.Color(153, 153, 153));
        LastNamMothARTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LastNamMothARTxt.setText(" اســم  الام");
        LastNamMothARTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LastNamMothARTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LastNamMothARTxtFocusGained(evt);
            }
        });
        LastNamMothARTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNamMothARTxtActionPerformed(evt);
            }
        });
        LastNamMothARTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LastNamMothARTxtKeyPressed(evt);
            }
        });

        txtProfission_Moth.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtProfission_Moth.setForeground(new java.awt.Color(153, 153, 153));
        txtProfission_Moth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProfission_Moth.setText("مهنـة الام");
        txtProfission_Moth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtProfission_Moth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProfission_MothFocusGained(evt);
            }
        });
        txtProfission_Moth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProfission_MothKeyPressed(evt);
            }
        });

        jLabel77.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel77.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel77.setText("مهنـة الام");

        jLabel72.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel72.setText("تـاريـخ الـميـلاد");

        jLabel80.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel80.setText("الــولايـــة           :");

        WilayaList.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        WilayaList.setAutoscrolls(true);
        WilayaList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WilayaListActionPerformed(evt);
            }
        });
        WilayaList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                WilayaListKeyPressed(evt);
            }
        });

        ComboxHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboxHomeActionPerformed(evt);
            }
        });

        jLabel88.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel88.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel88.setText("الــبلــديــة  :");

        jLabel78.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel78.setText(" الــعـنــوان          : ");

        txtAddress_Std.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAddress_Std.setForeground(new java.awt.Color(153, 153, 153));
        txtAddress_Std.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAddress_Std.setText(" الــعـنــوان ");
        txtAddress_Std.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAddress_Std.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAddress_StdFocusGained(evt);
            }
        });
        txtAddress_Std.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddress_StdKeyPressed(evt);
            }
        });

        jLabel81.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel81.setText("الــدائـــرة  :");

        txtDairaStd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDairaStd.setForeground(new java.awt.Color(153, 153, 153));
        txtDairaStd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDairaStd.setText("الــدائـــرة");
        txtDairaStd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDairaStd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDairaStdFocusGained(evt);
            }
        });
        txtDairaStd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDairaStdKeyPressed(evt);
            }
        });

        jLabel82.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel82.setText("رقم التسجيل");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtProfission_Moth))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(ComboxHome, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNam_mother, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel73, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPlcBirth_std, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                            .addComponent(txtProfission_Std, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel74, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtSurNam_std, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel76, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LastNamMothARTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel161, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNam_Father, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel72, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNam_std)
                                            .addComponent(DatBirth_std)
                                            .addComponent(jLabel75, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel77, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel81, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txt_NumInsc))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel82, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDairaStd, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtAddress_Std, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WilayaList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel80, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel78, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_NumInsc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel71))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNam_std, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSurNam_std, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel73)
                    .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPlcBirth_std)
                    .addComponent(DatBirth_std, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel74)
                    .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNam_Father, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfission_Std, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNam_mother, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel161, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel76))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LastNamMothARTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel77)
                .addGap(6, 6, 6)
                .addComponent(txtProfission_Moth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel88))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComboxHome, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(WilayaList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel78)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddress_Std, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel81)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDairaStd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setPreferredSize(new java.awt.Dimension(1000, 150));

        National_list.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        National_list.setAutoscrolls(true);
        National_list.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                National_listKeyPressed(evt);
            }
        });

        jLabel67.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("الجناح:");

        PavillonPanInf.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PavillonPanInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PavillonPanInfActionPerformed(evt);
            }
        });

        RomPvinPanInf.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel65.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel65.setText("الغرفة");

        jCheckBox1.setBackground(new java.awt.Color(204, 204, 204));
        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jCheckBox1.setText("الغاء حجز الغرفة");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jCheckBox1.setBorderPainted(true);
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel79.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel79.setText("الــــجــنـســيـــة  :");

        jLabel83.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel83.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel83.setText("الحـالـــة  العــائــلـيـة  :");

        Sti_Single1.setBackground(new java.awt.Color(255, 255, 255));
        Sti_Single1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Sti_Single1.setSelected(true);
        Sti_Single1.setText("اعـــزب");
        Sti_Single1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Sti_Single1.setBorderPainted(true);
        Sti_Single1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Sti_Single1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sti_Single1ActionPerformed(evt);
            }
        });
        Sti_Single1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Sti_Single1KeyPressed(evt);
            }
        });

        Std_Maried.setBackground(new java.awt.Color(255, 255, 255));
        Std_Maried.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Std_Maried.setText("مــتــزوج");
        Std_Maried.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Std_Maried.setBorderPainted(true);
        Std_Maried.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Std_Maried.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Std_MariedActionPerformed(evt);
            }
        });

        CheckMale.setBackground(new java.awt.Color(255, 255, 255));
        CheckMale.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CheckMale.setSelected(true);
        CheckMale.setText("مذكر");
        CheckMale.setToolTipText("");
        CheckMale.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        CheckMale.setBorderPainted(true);
        CheckMale.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CheckMale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CheckMale.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        CheckMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckMaleActionPerformed(evt);
            }
        });

        checkFemal.setBackground(new java.awt.Color(255, 255, 255));
        checkFemal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkFemal.setText("مؤنث");
        checkFemal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        checkFemal.setBorderPainted(true);
        checkFemal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        checkFemal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkFemal.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        checkFemal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFemalActionPerformed(evt);
            }
        });

        jLabel84.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel84.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel84.setText("الــبـكـالــوريـا  دورة ");

        jLabel104.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel104.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel104.setText("الــمــعــدل ");

        TtxtBacYear.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        TtxtBacYear.setForeground(new java.awt.Color(204, 204, 204));
        TtxtBacYear.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TtxtBacYear.setText("2018");
        TtxtBacYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TtxtBacYear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TtxtBacYearFocusGained(evt);
            }
        });
        TtxtBacYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TtxtBacYearKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TtxtBacYearKeyTyped(evt);
            }
        });

        txtBacMoy.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtBacMoy.setForeground(new java.awt.Color(204, 204, 204));
        txtBacMoy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBacMoy.setText("00.00");
        txtBacMoy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtBacMoy.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBacMoyFocusGained(evt);
            }
        });
        txtBacMoy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBacMoyKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBacMoyKeyTyped(evt);
            }
        });

        jLabel89.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel89.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel89.setText("مــكـان الــحــصـول عــلــي الــبــكـالـــوريـــا ");

        txtPlaceGetBac.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtPlaceGetBac.setForeground(new java.awt.Color(153, 153, 153));
        txtPlaceGetBac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPlaceGetBac.setText("مــكـان الــحــصـول عــلــي الــبــكـالـــوريـــا ");
        txtPlaceGetBac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPlaceGetBac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPlaceGetBacFocusGained(evt);
            }
        });
        txtPlaceGetBac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPlaceGetBacKeyPressed(evt);
            }
        });

        jLabel90.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel90.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel90.setText("التخـصص الدراســـــــي      ");

        txtBranch_std.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtBranch_std.setAutoscrolls(true);
        txtBranch_std.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBranch_stdKeyPressed(evt);
            }
        });

        jLabel91.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel91.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel91.setText("تاريخ التسجيل بالجامعة ");

        DatInscrpInUniv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DatInscrpInUniv.setForeground(java.awt.Color.blue);
        try {
            DatInscrpInUniv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        DatInscrpInUniv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DatInscrpInUniv.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SimpleDateFormat formatDat=new SimpleDateFormat("dd/MM/YYYY");
        String DatInscrpStr=formatDat.format(new Date());

        DatInscrpInUniv.setText(DatInscrpStr);
        DatInscrpInUniv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DatInscrpInUnivKeyPressed(evt);
            }
        });

        LevelStd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        LevelStd.setAutoscrolls(true);
        LevelStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LevelStdActionPerformed(evt);
            }
        });
        LevelStd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LevelStdKeyPressed(evt);
            }
        });

        jLabel87.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel87.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel87.setText("المسـتوي الدراسي");

        jLabel92.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel92.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel92.setText("الـــكـــلــــيــــة");

        txtDepa_Std.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtDepa_Std.setAutoscrolls(true);
        txtDepa_Std.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDepa_StdKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel92)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDepa_Std, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(LevelStd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel87, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel91, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DatInscrpInUniv, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(txtBranch_std, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel83, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(Std_Maried, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Sti_Single1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel79, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                        .addComponent(CheckMale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkFemal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel104, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtBacMoy))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TtxtBacYear)
                                            .addComponent(jLabel84, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(National_list, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPlaceGetBac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(jLabel89, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PavillonPanInf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel65, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(RomPvinPanInf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel67, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(National_list, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel83)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sti_Single1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Std_Maried, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkFemal)
                            .addComponent(CheckMale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel67)
                            .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RomPvinPanInf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PavillonPanInf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel104, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBacMoy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TtxtBacYear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel89, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txtPlaceGetBac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel90)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBranch_std, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel91)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DatInscrpInUniv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel87)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LevelStd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel92)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDepa_Std, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(cLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(cLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 474, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNam_stdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNam_stdFocusGained
        if (txtNam_std.getText().equals(".......................................................................")) {
            txtNam_std.setText("");
        }
        txtNam_std.setForeground(Color.blue);
    }//GEN-LAST:event_txtNam_stdFocusGained

    private void txtNam_stdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNam_stdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtSurNam_std.requestFocus();
        }
    }//GEN-LAST:event_txtNam_stdKeyPressed

    private void DatBirth_stdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DatBirth_stdFocusGained
        DatBirth_std.setForeground(Color.blue);
    }//GEN-LAST:event_DatBirth_stdFocusGained

    private void DatBirth_stdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DatBirth_stdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtPlcBirth_std.requestFocus();
        }
    }//GEN-LAST:event_DatBirth_stdKeyPressed

    private void txtSurNam_stdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSurNam_stdFocusGained
        if (txtSurNam_std.getText().equals("........................................................................")) {
            txtSurNam_std.setText("");
        }
        txtSurNam_std.setForeground(Color.blue);
    }//GEN-LAST:event_txtSurNam_stdFocusGained

    private void txtSurNam_stdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSurNam_stdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DatBirth_std.requestFocus();
        }
    }//GEN-LAST:event_txtSurNam_stdKeyPressed

    private void txtPlcBirth_stdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlcBirth_stdFocusGained
        if (txtPlcBirth_std.getText().equals("................................................................")) {
            txtPlcBirth_std.setText("");
        }
        txtPlcBirth_std.setForeground(Color.blue);
    }//GEN-LAST:event_txtPlcBirth_stdFocusGained

    private void txtPlcBirth_stdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlcBirth_stdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtNam_Father.requestFocus();
        }
    }//GEN-LAST:event_txtPlcBirth_stdKeyPressed

    private void txtNam_FatherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNam_FatherFocusGained
        if (txtNam_Father.getText().equals(".......................................................................")) {
            txtNam_Father.setText("");
        }
        txtNam_Father.setForeground(Color.blue);
    }//GEN-LAST:event_txtNam_FatherFocusGained

    private void txtNam_FatherKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNam_FatherKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtProfission_Std.requestFocus();
        }
    }//GEN-LAST:event_txtNam_FatherKeyPressed

    private void txtProfission_StdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProfission_StdFocusGained
        if (txtProfission_Std.getText().equals("........................................................................")) {
            txtProfission_Std.setText("");
        }
        txtProfission_Std.setForeground(Color.blue);
    }//GEN-LAST:event_txtProfission_StdFocusGained

    private void txtProfission_StdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfission_StdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfission_StdActionPerformed

    private void txtProfission_StdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProfission_StdKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtNam_mother.requestFocus();
        }
    }//GEN-LAST:event_txtProfission_StdKeyPressed

    private void txtNam_motherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNam_motherFocusGained
        if (txtNam_mother.getText().equals("..................................................................")) {
            txtNam_mother.setText("");
        }
        txtNam_mother.setForeground(Color.blue);
    }//GEN-LAST:event_txtNam_motherFocusGained

    private void txtNam_motherKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNam_motherKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            LastNamMothARTxt.requestFocus();
            //txtProfission_Moth.requestFocus();
        }
    }//GEN-LAST:event_txtNam_motherKeyPressed

    private void LastNamMothARTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LastNamMothARTxtFocusGained
        if (LastNamMothARTxt.getText().equals("..............................")) {
            LastNamMothARTxt.setText("");
        }
        LastNamMothARTxt.setForeground(Color.blue);
    }//GEN-LAST:event_LastNamMothARTxtFocusGained

    private void LastNamMothARTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNamMothARTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNamMothARTxtActionPerformed

    private void LastNamMothARTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LastNamMothARTxtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            txtProfission_Moth.requestFocus();
        }
    }//GEN-LAST:event_LastNamMothARTxtKeyPressed

    private void txtProfission_MothFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProfission_MothFocusGained
        if (txtProfission_Moth.getText().equals(".......................................................................")) {
            txtProfission_Moth.setText("");
        }
        txtProfission_Moth.setForeground(Color.blue);
    }//GEN-LAST:event_txtProfission_MothFocusGained

    private void txtProfission_MothKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProfission_MothKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtAddress_Std.requestFocus();
        }
    }//GEN-LAST:event_txtProfission_MothKeyPressed

    private void txt_NumInscFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NumInscFocusGained
        if (txt_NumInsc.getText().equals("رقــم تــسجـيــل الــبـكــالــوريــا ")) {
            txt_NumInsc.setText("");
        }
        txt_NumInsc.setForeground(Color.RED);
    }//GEN-LAST:event_txt_NumInscFocusGained

    private void txt_NumInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NumInscActionPerformed
        /*  SimpleDateFormat Frmat=new SimpleDateFormat("yy");
        String AnnIns=Frmat.format(new Date());
        String NumInsc=txt_NumInsc.getText();
        Get_Nev_Inf =new Get_Nev_Inf(this);
        String NumInscription="";
        if (NumInsc.startsWith((AnnIns+"/"))) {
            NumInscription= NumInsc.substring(3);
        }else{
            NumInscription=NumInsc;
        }
        Calendar cal = Calendar.getInstance();
        cal.setTime(new Date());
        int year = cal.get(Calendar.YEAR);
        int i =Get_Nev_Inf.Get_Info_Nev_Res(NumInscription, txtNam_std, txtSurNam_std,
            DatBirth_std,txtPlcBirth_std,txtNam_Father, txtNam_mother,
            LastNamMothARTxt, txtCommuneStd, National_list, CheckMale, checkFemal,
            txtBranch_std, LevelStd,year);

        if(i!=1){
            NamFR="";
            PrénomFR="";
            NamFatheFr="";
            NamMatherFR="";
            LastMatherFR="";
            PlcFR="";
            */
            /*messagerror = new MessageErrorControl(this, true, " الرقـــم غـيـر مــوجـود الـرجـاء الـتأكـد مـنـه");
            messagerror.setVisible(true);*/
            /*jLabel60.setText("الرقم غير موجود");
            Initialise_Student_Resident();
            txt_NumInsc.setText(NumInsc);
            txt_NumInsc.setForeground(Color.red);
        }*/
        txtNam_std.requestFocus();
    }//GEN-LAST:event_txt_NumInscActionPerformed

    private void txt_NumInscKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NumInscKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtNam_std.requestFocus();
        }
    }//GEN-LAST:event_txt_NumInscKeyPressed

    private void txtNam_stdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNam_stdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNam_stdActionPerformed

    private void WilayaListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WilayaListActionPerformed
        F.FillTableCommune_Combobox((String) WilayaList.getSelectedItem(), null, ComboxHome, 1);
    }//GEN-LAST:event_WilayaListActionPerformed

    private void WilayaListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WilayaListKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtDairaStd.requestFocus();
        }
    }//GEN-LAST:event_WilayaListKeyPressed

    private void ComboxHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboxHomeActionPerformed
        //        String CommuneSlc=(String)ComboxHome.getSelectedItem();
        //        if (!CommuneSlc.equals("اختر البلدية")) {
            //            CommuneSlc.setText(CommuneSlc);
            //        }
    }//GEN-LAST:event_ComboxHomeActionPerformed

    private void txtDairaStdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDairaStdFocusGained
        if (txtDairaStd.getText().equals("........................................")) {
            txtDairaStd.setText("");
        }
        txtDairaStd.setForeground(Color.blue);
    }//GEN-LAST:event_txtDairaStdFocusGained

    private void txtDairaStdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDairaStdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ComboxHome.requestFocus();
        }
    }//GEN-LAST:event_txtDairaStdKeyPressed

    private void txtAddress_StdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddress_StdFocusGained
        if (txtAddress_Std.getText().equals("...............................................................................................................................................................")) {
            txtAddress_Std.setText("");
        }
        txtAddress_Std.setForeground(Color.blue);
    }//GEN-LAST:event_txtAddress_StdFocusGained

    private void txtAddress_StdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddress_StdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            WilayaList.requestFocus();
        }
    }//GEN-LAST:event_txtAddress_StdKeyPressed

    private void National_listKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_National_listKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            CheckMale.requestFocus();
        }
    }//GEN-LAST:event_National_listKeyPressed

    private void PavillonPanInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PavillonPanInfActionPerformed
        RoomRemplissage.FillComboboxRooms(RomPvinPanInf, (String) PavillonPanInf.getSelectedItem());
    }//GEN-LAST:event_PavillonPanInfActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            PavillonPanInf.setEnabled(false);
            RomPvinPanInf.setEnabled(false);
        } else {
            PavillonPanInf.setEnabled(true);
            RomPvinPanInf.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void Sti_Single1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sti_Single1ActionPerformed
        if (Sti_Single1.isSelected()) {
            Std_Maried.setSelected(false);
            SituationFam = Sti_Single1.getText();
            TtxtBacYear.requestFocus();
        } else {
            Std_Maried.setSelected(true);
            SituationFam = Std_Maried.getText();

        }
    }//GEN-LAST:event_Sti_Single1ActionPerformed

    private void Sti_Single1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Sti_Single1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sti_Single1KeyPressed

    private void Std_MariedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Std_MariedActionPerformed
        if (Std_Maried.isSelected()) {
            Sti_Single1.setSelected(false);
            SituationFam = Std_Maried.getText();
            TtxtBacYear.requestFocus();
        } else {
            Sti_Single1.setSelected(true);
            SituationFam = Sti_Single1.getText();
            TtxtBacYear.requestFocus();
        }
    }//GEN-LAST:event_Std_MariedActionPerformed

    private void CheckMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckMaleActionPerformed
        if (CheckMale.isSelected()) {
            checkFemal.setSelected(false);
            Gender = 1;
            Sti_Single1.requestFocus();
        } else {
            checkFemal.setSelected(true);
            Sti_Single1.requestFocus();
            Gender = 2;
        }
    }//GEN-LAST:event_CheckMaleActionPerformed

    private void checkFemalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFemalActionPerformed
        if (checkFemal.isSelected()) {
            CheckMale.setSelected(false);
            Gender = 2;
            Sti_Single1.requestFocus();
        } else {
            CheckMale.setSelected(true);
            Gender = 1;
        }
    }//GEN-LAST:event_checkFemalActionPerformed

    private void TtxtBacYearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TtxtBacYearFocusGained
        TtxtBacYear.setForeground(Color.black);
    }//GEN-LAST:event_TtxtBacYearFocusGained

    private void TtxtBacYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TtxtBacYearKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtBacMoy.requestFocus();
        }
    }//GEN-LAST:event_TtxtBacYearKeyPressed

    private void TtxtBacYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TtxtBacYearKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_BACK_SPACE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_TtxtBacYearKeyTyped

    private void txtBacMoyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBacMoyFocusGained
        txtBacMoy.setForeground(Color.black);
    }//GEN-LAST:event_txtBacMoyFocusGained

    private void txtBacMoyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBacMoyKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtPlaceGetBac.requestFocus();
        }
    }//GEN-LAST:event_txtBacMoyKeyPressed

    private void txtBacMoyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBacMoyKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_BACK_SPACE) || c == '.')) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtBacMoyKeyTyped

    private void txtPlaceGetBacFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlaceGetBacFocusGained
        if (txtPlaceGetBac.getText().equals("............................................................................................................................")) {
            txtPlaceGetBac.setText("");
        }
        txtPlaceGetBac.setForeground(Color.blue);
    }//GEN-LAST:event_txtPlaceGetBacFocusGained

    private void txtPlaceGetBacKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlaceGetBacKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtBranch_std.requestFocus();
        }
    }//GEN-LAST:event_txtPlaceGetBacKeyPressed

    private void txtBranch_stdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBranch_stdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DatInscrpInUniv.requestFocus();
        }
    }//GEN-LAST:event_txtBranch_stdKeyPressed

    private void DatInscrpInUnivKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DatInscrpInUnivKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            LevelStd.requestFocus();
        }
    }//GEN-LAST:event_DatInscrpInUnivKeyPressed

    private void LevelStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LevelStdActionPerformed
        // TODO add your handling code here:
        Level = (String) LevelStd.getSelectedItem();
    }//GEN-LAST:event_LevelStdActionPerformed

    private void LevelStdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LevelStdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtDepa_Std.requestFocus();
            txtDepa_Std.showPopup();
        }
    }//GEN-LAST:event_LevelStdKeyPressed

    private void txtDepa_StdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDepa_StdKeyPressed
        // TODO add your handling code here:

        //BtnSaveStd.requestFocus();

        //BtnSaveStd.setBackground(Color.red);
    }//GEN-LAST:event_txtDepa_StdKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckMale;
    private javax.swing.JComboBox<String> ComboxHome;
    private javax.swing.JFormattedTextField DatBirth_std;
    private javax.swing.JFormattedTextField DatInscrpInUniv;
    private javax.swing.JTextField LastNamMothARTxt;
    private javax.swing.JComboBox<String> LevelStd;
    private javax.swing.JComboBox<String> National_list;
    private javax.swing.JComboBox<String> PavillonPanInf;
    private javax.swing.JComboBox<String> RomPvinPanInf;
    private javax.swing.JCheckBox Std_Maried;
    private javax.swing.JCheckBox Sti_Single1;
    private javax.swing.JTextField TtxtBacYear;
    private javax.swing.JComboBox<String> WilayaList;
    private ViewMyPrj.CLabel cLabel1;
    private javax.swing.JCheckBox checkFemal;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField txtAddress_Std;
    private javax.swing.JTextField txtBacMoy;
    private javax.swing.JComboBox<String> txtBranch_std;
    private javax.swing.JTextField txtDairaStd;
    private javax.swing.JComboBox<String> txtDepa_Std;
    private javax.swing.JTextField txtNam_Father;
    private javax.swing.JTextField txtNam_mother;
    private javax.swing.JTextField txtNam_std;
    private javax.swing.JTextField txtPlaceGetBac;
    private javax.swing.JTextField txtPlcBirth_std;
    private javax.swing.JTextField txtProfission_Moth;
    private javax.swing.JTextField txtProfission_Std;
    private javax.swing.JTextField txtSurNam_std;
    private javax.swing.JTextField txt_NumInsc;
    // End of variables declaration//GEN-END:variables
}
