/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formes;


import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import residence.Get_Info_DB;

/**
 *
 * @author client
 */
public class AddFaculty extends javax.swing.JFrame {

    Get_Info_DB get_Info_DB=new Get_Info_DB();
    
    public AddFaculty() {
        initComponents();
        DesignTable(TabFaculty);
    }

    public void DesignTable(JTable table){
        table.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,12));
        table.getTableHeader().setOpaque(false);
        table.getTableHeader().setBackground(new Color(32,136,203));
        table.getTableHeader().setForeground(new Color(255,255,255));
        table.setRowHeight(25);
        table.setBackground(new Color(255,255,255));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PanFaculty = new javax.swing.JPanel();
        FacultyAr = new javax.swing.JTextField();
        FacultyFr = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        TabFaculty = new javax.swing.JTable();
        BtnUpdtSaveWilaya = new View.ButtonView();
        buttonView4 = new View.ButtonView();
        buttonView5 = new View.ButtonView();
        buttonView6 = new View.ButtonView();
        buttonView7 = new View.ButtonView();
        SearchWilayaTXT = new View.TextField();
        LabFacultyFr = new javax.swing.JLabel();
        LabFacultyAr = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 6, 40, 30));

        PanFaculty.setBackground(new java.awt.Color(255, 255, 255));
        PanFaculty.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FacultyAr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        FacultyAr.setForeground(new java.awt.Color(153, 153, 153));
        FacultyAr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FacultyAr.setText("ادخــــل الــكـــلـــيـــة ");
        FacultyAr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FacultyAr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FacultyArFocusGained(evt);
            }
        });
        FacultyAr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultyArActionPerformed(evt);
            }
        });
        PanFaculty.add(FacultyAr, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 250, 30));

        FacultyFr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        FacultyFr.setForeground(new java.awt.Color(153, 153, 153));
        FacultyFr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FacultyFr.setText("Faculté");
        FacultyFr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FacultyFr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FacultyFrFocusGained(evt);
            }
        });
        FacultyFr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultyFrActionPerformed(evt);
            }
        });
        PanFaculty.add(FacultyFr, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 250, 30));

        TabFaculty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TabFaculty.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TabFaculty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Faculty", "الــكـــلـــيـــة", "ID"
            }
        ));
        TabFaculty.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TabFaculty.setRowHeight(22);
        TabFaculty.setSelectionBackground(new java.awt.Color(51, 153, 0));
        TabFaculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabFacultyMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TabFaculty);

        PanFaculty.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 570, 320));

        BtnUpdtSaveWilaya.setBackground(new java.awt.Color(0, 102, 102));
        BtnUpdtSaveWilaya.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpdtSaveWilaya.setText("حفظ");
        BtnUpdtSaveWilaya.setBackgroundPainted(true);
        BtnUpdtSaveWilaya.setBorderPainted(false);
        BtnUpdtSaveWilaya.setEntred(false);
        BtnUpdtSaveWilaya.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnUpdtSaveWilaya.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnUpdtSaveWilaya.setRounded(true);
        BtnUpdtSaveWilaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdtSaveWilayaActionPerformed(evt);
            }
        });
        PanFaculty.add(BtnUpdtSaveWilaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 110, 40));

        buttonView4.setBackground(new java.awt.Color(0, 102, 102));
        buttonView4.setForeground(new java.awt.Color(255, 255, 255));
        buttonView4.setText("الغاء");
        buttonView4.setBackgroundPainted(true);
        buttonView4.setBorderPainted(false);
        buttonView4.setEntred(false);
        buttonView4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonView4.setRounded(true);
        buttonView4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonView4ActionPerformed(evt);
            }
        });
        PanFaculty.add(buttonView4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 110, 40));

        buttonView5.setBackground(new java.awt.Color(0, 102, 102));
        buttonView5.setForeground(new java.awt.Color(255, 255, 255));
        buttonView5.setText("حـــذف");
        buttonView5.setBackgroundPainted(true);
        buttonView5.setBorderPainted(false);
        buttonView5.setEntred(false);
        buttonView5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        buttonView5.setRounded(true);
        buttonView5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonView5ActionPerformed(evt);
            }
        });
        PanFaculty.add(buttonView5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 40));

        buttonView6.setBackground(new java.awt.Color(0, 102, 102));
        buttonView6.setForeground(new java.awt.Color(255, 255, 255));
        buttonView6.setText("خروج");
        buttonView6.setBackgroundPainted(true);
        buttonView6.setBorderPainted(false);
        buttonView6.setEntred(false);
        buttonView6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonView6.setRounded(true);
        buttonView6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonView6ActionPerformed(evt);
            }
        });
        PanFaculty.add(buttonView6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 110, 40));

        buttonView7.setBackground(new java.awt.Color(0, 102, 102));
        buttonView7.setForeground(new java.awt.Color(255, 255, 255));
        buttonView7.setText("تـعـديـل");
        buttonView7.setBackgroundPainted(true);
        buttonView7.setBorderPainted(false);
        buttonView7.setEntred(false);
        buttonView7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        buttonView7.setRounded(true);
        buttonView7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonView7ActionPerformed(evt);
            }
        });
        PanFaculty.add(buttonView7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 100, 40));

        SearchWilayaTXT.setForeground(new java.awt.Color(204, 204, 204));
        SearchWilayaTXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SearchWilayaTXT.setText("البحث");
        SearchWilayaTXT.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        SearchWilayaTXT.setLabelText("");
        SearchWilayaTXT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchWilayaTXTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchWilayaTXTFocusLost(evt);
            }
        });
        SearchWilayaTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchWilayaTXTActionPerformed(evt);
            }
        });
        SearchWilayaTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchWilayaTXTKeyReleased(evt);
            }
        });
        PanFaculty.add(SearchWilayaTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 290, 40));

        LabFacultyFr.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        LabFacultyFr.setText("Faculté");
        PanFaculty.add(LabFacultyFr, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 60, 30));

        LabFacultyAr.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        LabFacultyAr.setText("الــكــلــيــة");
        PanFaculty.add(LabFacultyAr, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 60, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residence/Image/Edit_Mini.png"))); // NOI18N
        jLabel3.setText("  ");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });
        PanFaculty.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 30, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residence/Image/DelCrd.png"))); // NOI18N
        jLabel4.setText("  ");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });
        PanFaculty.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 30, 30));

        getContentPane().add(PanFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 53, 860, 470));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Faculté   إضــافــة كــلّــيــة");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 860, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FacultyArFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FacultyArFocusGained
        if(FacultyAr.getText().equals("ادخــــل الــكـــلـــيـــة ")){
            FacultyAr.setText("");
        }
        FacultyAr.setForeground(Color.BLACK);
    }//GEN-LAST:event_FacultyArFocusGained

    private void FacultyFrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FacultyFrFocusGained
        if(FacultyFr.getText().equals("Faculté")){
            FacultyFr.setText("");
        }
        FacultyFr.setForeground(Color.BLACK);
    }//GEN-LAST:event_FacultyFrFocusGained

    private void FacultyArActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultyArActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacultyArActionPerformed

    private void TabFacultyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabFacultyMouseClicked
        int RowSlc=TabFaculty.getSelectedRow();
        int idFaculty=(int) TabFaculty.getValueAt(RowSlc, 2);
        jLabel1.setText(idFaculty+"");
    }//GEN-LAST:event_TabFacultyMouseClicked

    private void BtnUpdtSaveWilayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdtSaveWilayaActionPerformed
      if(!FacultyAr.getText().equals("ادخــــل الــكـــلـــيـــة ") &&!FacultyAr.getText().equals("")){
       get_Info_DB.InsertIntoDB("Faculty", "NameFact", "NameFact_Fr",FacultyAr.getText() ,FacultyFr.getText());

        get_Info_DB.GetAllBranche(TabFaculty,"Id_Faculty","Faculty","NameFact_Fr", "NameFact");
        RemoveEle(TabFaculty);
       }
      
            initialisation();
    }//GEN-LAST:event_BtnUpdtSaveWilayaActionPerformed
    public void initialisation(){
    FacultyAr.setText("ادخــــل الــكـــلـــيـــة ");
    FacultyAr.setForeground(new Color(153,153,153));
    FacultyFr.setText("Faculty");
    FacultyFr.setForeground(new Color(153,153,153));
   
    }
    
    public void RemoveEle(JTable tab){
       int i=0;
      DefaultTableModel dftabMd=(DefaultTableModel)tab.getModel();
        while(i<tab.getRowCount()){
            String a=(String) tab.getValueAt(i,1);
            if(a.equals("/")){
                dftabMd.removeRow(i);
                break;
            }
            i++;
        }
    }
    
    private void buttonView4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView4ActionPerformed
        initialisation();
    }//GEN-LAST:event_buttonView4ActionPerformed

    private void buttonView5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView5ActionPerformed
             this.dispose();
    }//GEN-LAST:event_buttonView5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonView6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonView6ActionPerformed

    private void buttonView7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonView7ActionPerformed

    private void SearchWilayaTXTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchWilayaTXTFocusGained
        if (SearchWilayaTXT.getText().equals("البحث")) {
            SearchWilayaTXT.setText("");
            SearchWilayaTXT.setForeground(Color.black);
        }
    }//GEN-LAST:event_SearchWilayaTXTFocusGained

    private void SearchWilayaTXTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchWilayaTXTFocusLost
      
    }//GEN-LAST:event_SearchWilayaTXTFocusLost

    private void SearchWilayaTXTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchWilayaTXTKeyReleased


    }//GEN-LAST:event_SearchWilayaTXTKeyReleased

    private void SearchWilayaTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchWilayaTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchWilayaTXTActionPerformed

    private void FacultyFrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultyFrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacultyFrActionPerformed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jLabel3.setBackground(Color.red);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFaculty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.ButtonView BtnUpdtSaveWilaya;
    private javax.swing.JTextField FacultyAr;
    private javax.swing.JTextField FacultyFr;
    private javax.swing.JLabel LabFacultyAr;
    private javax.swing.JLabel LabFacultyFr;
    private javax.swing.JPanel PanFaculty;
    private View.TextField SearchWilayaTXT;
    private javax.swing.JTable TabFaculty;
    private View.ButtonView buttonView4;
    private View.ButtonView buttonView5;
    private View.ButtonView buttonView6;
    private View.ButtonView buttonView7;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
