/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formes;

import java.awt.Color;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import residence.Get_Info_DB;

/**
 *
 * @author client
 */
public class AddLavelStudy extends javax.swing.JFrame {

        Get_Info_DB get_Info_DB=new Get_Info_DB();

    public AddLavelStudy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PanFaculty = new javax.swing.JPanel();
        BtnUpdtSaveWilaya = new View.ButtonView();
        buttonView4 = new View.ButtonView();
        buttonView5 = new View.ButtonView();
        LevlStdAR = new javax.swing.JTextField();
        LevlStdFR = new javax.swing.JTextField();
        jScrollPane12 = new javax.swing.JScrollPane();
        LevelTab = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setBackground(new java.awt.Color(0, 153, 153));
        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("X");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 40, 30));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("   إضــافــة المستوي الدراسي ");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 800, 50));

        PanFaculty.setBackground(new java.awt.Color(255, 255, 255));
        PanFaculty.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnUpdtSaveWilaya.setBackground(new java.awt.Color(0, 102, 102));
        BtnUpdtSaveWilaya.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpdtSaveWilaya.setText("حفظ");
        BtnUpdtSaveWilaya.setBackgroundPainted(true);
        BtnUpdtSaveWilaya.setBorderPainted(false);
        BtnUpdtSaveWilaya.setEntred(false);
        BtnUpdtSaveWilaya.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnUpdtSaveWilaya.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnUpdtSaveWilaya.setRounded(true);
        BtnUpdtSaveWilaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdtSaveWilayaActionPerformed(evt);
            }
        });
        PanFaculty.add(BtnUpdtSaveWilaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 100, 30));

        buttonView4.setBackground(new java.awt.Color(0, 102, 102));
        buttonView4.setForeground(new java.awt.Color(255, 255, 255));
        buttonView4.setText("الغاء");
        buttonView4.setBackgroundPainted(true);
        buttonView4.setBorderPainted(false);
        buttonView4.setEntred(false);
        buttonView4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonView4.setRounded(true);
        buttonView4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonView4ActionPerformed(evt);
            }
        });
        PanFaculty.add(buttonView4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 100, 30));

        buttonView5.setBackground(new java.awt.Color(0, 102, 102));
        buttonView5.setForeground(new java.awt.Color(255, 255, 255));
        buttonView5.setText("خروج");
        buttonView5.setBackgroundPainted(true);
        buttonView5.setBorderPainted(false);
        buttonView5.setEntred(false);
        buttonView5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonView5.setRounded(true);
        buttonView5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonView5ActionPerformed(evt);
            }
        });
        PanFaculty.add(buttonView5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 100, 30));

        LevlStdAR.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LevlStdAR.setForeground(new java.awt.Color(153, 153, 153));
        LevlStdAR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LevlStdAR.setText("ادخــــل المستوي الدراسي ");
        LevlStdAR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LevlStdAR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LevlStdARFocusGained(evt);
            }
        });
        LevlStdAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LevlStdARActionPerformed(evt);
            }
        });
        PanFaculty.add(LevlStdAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 470, 30));

        LevlStdFR.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LevlStdFR.setForeground(new java.awt.Color(153, 153, 153));
        LevlStdFR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LevlStdFR.setText("Code Niveau ");
        LevlStdFR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LevlStdFR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LevlStdFRFocusGained(evt);
            }
        });
        LevlStdFR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LevlStdFRActionPerformed(evt);
            }
        });
        PanFaculty.add(LevlStdFR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 470, 30));

        LevelTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LevelTab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LevelTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code Niveau", "المستوي الدراسي", "ID"
            }
        ));
        LevelTab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LevelTab.setRowHeight(22);
        LevelTab.setSelectionBackground(new java.awt.Color(51, 153, 0));
        LevelTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LevelTabMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(LevelTab);

        PanFaculty.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 720, 230));

        getContentPane().add(PanFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 43, 800, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void BtnUpdtSaveWilayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdtSaveWilayaActionPerformed
        if(!LevlStdAR.getText().equals("ادخــــل المستوي الدراسي ")&&!LevlStdAR.getText().equals("")){

                get_Info_DB.InsertIntoDB("Level_Study", "Level_study", "DescriptionLevel",LevlStdFR.getText() ,LevlStdAR.getText());

                get_Info_DB.GetAllBranche(LevelTab,"Id_LevelStudy","Level_Study","Level_study", "DescriptionLevel");

                RemoveEle(LevelTab);
            }
        
        initialisation();
    }//GEN-LAST:event_BtnUpdtSaveWilayaActionPerformed
     public void initialisation(){
    LevlStdAR.setText("ادخــــل المستوي الدراسي ");
    LevlStdAR.setForeground(new Color(153,153,153));
    LevlStdFR.setText("Code Niveau ");
    LevlStdFR.setForeground(new Color(153,153,153));

  }
     public void RemoveEle(JTable tab){
       int i=0;
      DefaultTableModel dftabMd=(DefaultTableModel)tab.getModel();
        while(i<tab.getRowCount()){
            String a=(String) tab.getValueAt(i,1);
            if(a.equals("/")){
                dftabMd.removeRow(i);
                break;
            }
            i++;
        }
    }
    private void buttonView4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView4ActionPerformed
        initialisation();
    }//GEN-LAST:event_buttonView4ActionPerformed

    private void buttonView5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonView5ActionPerformed

    private void LevlStdARFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LevlStdARFocusGained
        if(LevlStdAR.getText().equals("ادخــــل المستوي الدراسي ")){
            LevlStdAR.setText("");
        }
        LevlStdAR.setForeground(Color.BLACK);
    }//GEN-LAST:event_LevlStdARFocusGained

    private void LevlStdARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LevlStdARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LevlStdARActionPerformed

    private void LevlStdFRFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LevlStdFRFocusGained
        if(LevlStdFR.getText().equals("Code Niveau ")){
            LevlStdFR.setText("");
        }
        LevlStdFR.setForeground(Color.BLACK);
    }//GEN-LAST:event_LevlStdFRFocusGained

    private void LevlStdFRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LevlStdFRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LevlStdFRActionPerformed

    private void LevelTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LevelTabMouseClicked
      
    }//GEN-LAST:event_LevelTabMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddLavelStudy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddLavelStudy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddLavelStudy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddLavelStudy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddLavelStudy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.ButtonView BtnUpdtSaveWilaya;
    private javax.swing.JTable LevelTab;
    private javax.swing.JTextField LevlStdAR;
    private javax.swing.JTextField LevlStdFR;
    private javax.swing.JPanel PanFaculty;
    private javax.swing.JButton btnExit;
    private View.ButtonView buttonView4;
    private View.ButtonView buttonView5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane12;
    // End of variables declaration//GEN-END:variables
}
