/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formes;

import java.awt.Color;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import residence.Get_Info_DB;

/**
 *
 * @author client
 */
public class AddNationality extends javax.swing.JFrame {
    
    Get_Info_DB get_Info_DB=new Get_Info_DB();

    public AddNationality() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PanFaculty = new javax.swing.JPanel();
        BtnUpdtSaveWilaya = new View.ButtonView();
        buttonView4 = new View.ButtonView();
        buttonView5 = new View.ButtonView();
        NationalityAr = new javax.swing.JTextField();
        NationalityFr = new javax.swing.JTextField();
        jScrollPane11 = new javax.swing.JScrollPane();
        TabNationaliy = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setBackground(new java.awt.Color(0, 153, 153));
        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("X");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 40, 30));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nationalité   إضــافــة الـجــنــســيــة");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 790, 50));

        PanFaculty.setBackground(new java.awt.Color(255, 255, 255));
        PanFaculty.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnUpdtSaveWilaya.setBackground(new java.awt.Color(0, 102, 102));
        BtnUpdtSaveWilaya.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpdtSaveWilaya.setText("حفظ");
        BtnUpdtSaveWilaya.setBackgroundPainted(true);
        BtnUpdtSaveWilaya.setBorderPainted(false);
        BtnUpdtSaveWilaya.setEntred(false);
        BtnUpdtSaveWilaya.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnUpdtSaveWilaya.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnUpdtSaveWilaya.setRounded(true);
        BtnUpdtSaveWilaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdtSaveWilayaActionPerformed(evt);
            }
        });
        PanFaculty.add(BtnUpdtSaveWilaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 100, 30));

        buttonView4.setBackground(new java.awt.Color(0, 102, 102));
        buttonView4.setForeground(new java.awt.Color(255, 255, 255));
        buttonView4.setText("الغاء");
        buttonView4.setBackgroundPainted(true);
        buttonView4.setBorderPainted(false);
        buttonView4.setEntred(false);
        buttonView4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonView4.setRounded(true);
        buttonView4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonView4ActionPerformed(evt);
            }
        });
        PanFaculty.add(buttonView4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 100, 30));

        buttonView5.setBackground(new java.awt.Color(0, 102, 102));
        buttonView5.setForeground(new java.awt.Color(255, 255, 255));
        buttonView5.setText("خروج");
        buttonView5.setBackgroundPainted(true);
        buttonView5.setBorderPainted(false);
        buttonView5.setEntred(false);
        buttonView5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonView5.setRounded(true);
        buttonView5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonView5ActionPerformed(evt);
            }
        });
        PanFaculty.add(buttonView5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 100, 30));

        NationalityAr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NationalityAr.setForeground(new java.awt.Color(153, 153, 153));
        NationalityAr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NationalityAr.setText("ادخــــل الـجــنــســيــة ");
        NationalityAr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NationalityAr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NationalityArFocusGained(evt);
            }
        });
        NationalityAr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NationalityArActionPerformed(evt);
            }
        });
        PanFaculty.add(NationalityAr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 470, 30));

        NationalityFr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NationalityFr.setForeground(new java.awt.Color(153, 153, 153));
        NationalityFr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NationalityFr.setText("Nationalité ");
        NationalityFr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NationalityFr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NationalityFrFocusGained(evt);
            }
        });
        NationalityFr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NationalityFrActionPerformed(evt);
            }
        });
        PanFaculty.add(NationalityFr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 470, 30));

        TabNationaliy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TabNationaliy.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TabNationaliy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nationality", "الـجــنــســيــة", "ID"
            }
        ));
        TabNationaliy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TabNationaliy.setRowHeight(22);
        TabNationaliy.setSelectionBackground(new java.awt.Color(51, 153, 0));
        TabNationaliy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabNationaliyMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(TabNationaliy);

        PanFaculty.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 720, 260));

        getContentPane().add(PanFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 43, 790, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnUpdtSaveWilayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdtSaveWilayaActionPerformed
        if(!NationalityAr.getText().equals("ادخــــل الـجــنــســيــة ")&&!NationalityAr.getText().equals("")){
             get_Info_DB.InsertIntoDB("Nationalite", "Nationalite", "Nationalite_Fr",NationalityAr.getText() ,NationalityFr.getText());

                get_Info_DB.GetAllBranche(TabNationaliy,"Id_Nationalite","Nationalite","Nationalite_Fr", "Nationalite");
        
         RemoveEle(TabNationaliy);
             
       }
        initialisation();
    }//GEN-LAST:event_BtnUpdtSaveWilayaActionPerformed
    public void initialisation(){
    
    NationalityAr.setText("ادخــــل الـجــنــســيــة ");
    NationalityAr.setForeground(new Color(153,153,153));
    NationalityFr.setText("Nationalité");
    NationalityFr.setForeground(new Color(153,153,153));
  }
    public void RemoveEle(JTable tab){
       int i=0;
      DefaultTableModel dftabMd=(DefaultTableModel)tab.getModel();
        while(i<tab.getRowCount()){
            String a=(String) tab.getValueAt(i,1);
            if(a.equals("/")){
                dftabMd.removeRow(i);
                break;
            }
            i++;
        }
    }
    private void buttonView4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView4ActionPerformed
        initialisation();
    }//GEN-LAST:event_buttonView4ActionPerformed

    private void buttonView5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonView5ActionPerformed

    private void NationalityArFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NationalityArFocusGained
        if(NationalityAr.getText().equals("ادخــــل الـجــنــســيــة ")){
            NationalityAr.setText("");
        }
        NationalityAr.setForeground(Color.WHITE);
    }//GEN-LAST:event_NationalityArFocusGained

    private void NationalityFrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NationalityFrFocusGained
        if(NationalityFr.getText().equals("Nationalité")){
            NationalityFr.setText("");
        }
        NationalityFr.setForeground(Color.WHITE);
    }//GEN-LAST:event_NationalityFrFocusGained

    private void NationalityFrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NationalityFrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NationalityFrActionPerformed

    private void TabNationaliyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabNationaliyMouseClicked

    }//GEN-LAST:event_TabNationaliyMouseClicked

    private void NationalityArActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NationalityArActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NationalityArActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNationality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNationality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNationality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNationality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNationality().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.ButtonView BtnUpdtSaveWilaya;
    private javax.swing.JTextField NationalityAr;
    private javax.swing.JTextField NationalityFr;
    private javax.swing.JPanel PanFaculty;
    private javax.swing.JTable TabNationaliy;
    private javax.swing.JButton btnExit;
    private View.ButtonView buttonView4;
    private View.ButtonView buttonView5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane11;
    // End of variables declaration//GEN-END:variables
}
