/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewMyPrj;
import java.awt.event.KeyEvent;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import residence.ConnectionDB;
import residence.TimeFormatter;
/**
 *
 * @author farid
 */
public class FormTestFreeDesignLayout extends javax.swing.JFrame {

    /**
     * Creates new form FormTestFreeDesignLayout
     */
    public FormTestFreeDesignLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNam_std = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        MaskFormatter formatter3 = new TimeFormatter();
        DatBirth_std = new javax.swing.JFormattedTextField(formatter3);
        jLabel71 = new javax.swing.JLabel();
        txtSurNam_std = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        txtPlcBirth_std = new javax.swing.JTextField();
        txtNam_Father = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        txtProfission_Std = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jLabel161 = new javax.swing.JLabel();
        txtNam_mother = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        LastNamMothARTxt = new javax.swing.JTextField();
        txtProfission_Moth = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        WilayaList = new javax.swing.JComboBox<>();
        jLabel80 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        ComboxHome = new javax.swing.JComboBox<>();
        jLabel81 = new javax.swing.JLabel();
        txtDairaStd = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        txtAddress_Std = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        National_list = new javax.swing.JComboBox<>();
        Sti_Single1 = new javax.swing.JCheckBox();
        Std_Maried = new javax.swing.JCheckBox();
        CheckMale = new javax.swing.JCheckBox();
        checkFemal = new javax.swing.JCheckBox();
        PavillonPanInf = new javax.swing.JComboBox<>();
        jLabel67 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        RomPvinPanInf = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        ConnectionDB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("الاســــــم");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        jPanel4.add(jLabel2, gridBagConstraints);

        txtNam_std.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtNam_std.setForeground(new java.awt.Color(153, 153, 153));
        txtNam_std.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNam_std.setText("الاسم");
        txtNam_std.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNam_std.setPreferredSize(new java.awt.Dimension(100, 30));
        txtNam_std.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNam_stdFocusGained(evt);
            }
        });
        txtNam_std.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNam_stdKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        jPanel4.add(txtNam_std, gridBagConstraints);

        jLabel72.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel72.setText("تـاريـخ الـميـلاد");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 30);
        jPanel4.add(jLabel72, gridBagConstraints);

        DatBirth_std.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DatBirth_std.setForeground(new java.awt.Color(153, 153, 153));
        try {
            DatBirth_std.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        DatBirth_std.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DatBirth_std.setFont(new java.awt.Font("Times New Roman", 1,16));
        DatBirth_std.setPreferredSize(new java.awt.Dimension(100, 30));
        DatBirth_std.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DatBirth_stdFocusGained(evt);
            }
        });
        DatBirth_std.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DatBirth_stdKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 30);
        jPanel4.add(DatBirth_std, gridBagConstraints);

        jLabel71.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel71.setText("الـلـــقـــب");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel4.add(jLabel71, gridBagConstraints);

        txtSurNam_std.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtSurNam_std.setForeground(new java.awt.Color(153, 153, 153));
        txtSurNam_std.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSurNam_std.setText("الـلـــقـــب");
        txtSurNam_std.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSurNam_std.setPreferredSize(new java.awt.Dimension(100, 30));
        txtSurNam_std.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSurNam_stdFocusGained(evt);
            }
        });
        txtSurNam_std.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSurNam_stdKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel4.add(txtSurNam_std, gridBagConstraints);

        jLabel73.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel73.setText("مــكـان الـميــلاد");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 20);
        jPanel4.add(jLabel73, gridBagConstraints);

        txtPlcBirth_std.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtPlcBirth_std.setForeground(new java.awt.Color(153, 153, 153));
        txtPlcBirth_std.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPlcBirth_std.setText("مــكـان الـميــلاد");
        txtPlcBirth_std.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPlcBirth_std.setPreferredSize(new java.awt.Dimension(100, 30));
        txtPlcBirth_std.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPlcBirth_stdFocusGained(evt);
            }
        });
        txtPlcBirth_std.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPlcBirth_stdKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 20);
        jPanel4.add(txtPlcBirth_std, gridBagConstraints);

        txtNam_Father.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtNam_Father.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNam_Father.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNam_Father.setPreferredSize(new java.awt.Dimension(100, 30));
        txtNam_Father.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNam_FatherFocusGained(evt);
            }
        });
        txtNam_Father.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNam_FatherKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        jPanel4.add(txtNam_Father, gridBagConstraints);

        jLabel75.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel75.setText("اســــم الأب");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        jPanel4.add(jLabel75, gridBagConstraints);

        txtProfission_Std.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtProfission_Std.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProfission_Std.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtProfission_Std.setPreferredSize(new java.awt.Dimension(100, 30));
        txtProfission_Std.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProfission_StdFocusGained(evt);
            }
        });
        txtProfission_Std.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfission_StdActionPerformed(evt);
            }
        });
        txtProfission_Std.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProfission_StdKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel4.add(txtProfission_Std, gridBagConstraints);

        jLabel74.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel74.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel74.setText("مهنــة الاب ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel4.add(jLabel74, gridBagConstraints);

        jLabel161.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel161.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel161.setText(" اســم  الام");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 30);
        jPanel4.add(jLabel161, gridBagConstraints);

        txtNam_mother.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtNam_mother.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNam_mother.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNam_mother.setPreferredSize(new java.awt.Dimension(100, 30));
        txtNam_mother.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNam_motherFocusGained(evt);
            }
        });
        txtNam_mother.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNam_motherKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 30);
        jPanel4.add(txtNam_mother, gridBagConstraints);

        jLabel76.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel76.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel76.setText("لفب  الام");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 20);
        jPanel4.add(jLabel76, gridBagConstraints);

        LastNamMothARTxt.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        LastNamMothARTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LastNamMothARTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LastNamMothARTxt.setPreferredSize(new java.awt.Dimension(100, 30));
        LastNamMothARTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LastNamMothARTxtFocusGained(evt);
            }
        });
        LastNamMothARTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNamMothARTxtActionPerformed(evt);
            }
        });
        LastNamMothARTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LastNamMothARTxtKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 20);
        jPanel4.add(LastNamMothARTxt, gridBagConstraints);

        txtProfission_Moth.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtProfission_Moth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProfission_Moth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtProfission_Moth.setPreferredSize(new java.awt.Dimension(100, 30));
        txtProfission_Moth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProfission_MothFocusGained(evt);
            }
        });
        txtProfission_Moth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProfission_MothKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        jPanel4.add(txtProfission_Moth, gridBagConstraints);

        jLabel77.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel77.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel77.setText("مهنـة الام");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        jPanel4.add(jLabel77, gridBagConstraints);

        jLabel60.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 51, 51));
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 0, 0);
        jPanel4.add(jLabel60, gridBagConstraints);

        jLabel82.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(7, 6, 0, 0);
        jPanel4.add(jLabel82, gridBagConstraints);

        WilayaList.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        WilayaList.setAutoscrolls(true);
        WilayaList.setPreferredSize(new java.awt.Dimension(100, 30));
        WilayaList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WilayaListActionPerformed(evt);
            }
        });
        WilayaList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                WilayaListKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel4.add(WilayaList, gridBagConstraints);

        jLabel80.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel80.setText("الــولايـــة           :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(jLabel80, gridBagConstraints);

        jLabel88.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel88.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel88.setText("الــبلــديــة  :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 30);
        jPanel4.add(jLabel88, gridBagConstraints);

        ComboxHome.setPreferredSize(new java.awt.Dimension(100, 30));
        ComboxHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboxHomeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 30);
        jPanel4.add(ComboxHome, gridBagConstraints);

        jLabel81.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel81.setText("الــدائـــرة");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 20);
        jPanel4.add(jLabel81, gridBagConstraints);

        txtDairaStd.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtDairaStd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDairaStd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDairaStd.setPreferredSize(new java.awt.Dimension(100, 30));
        txtDairaStd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDairaStdFocusGained(evt);
            }
        });
        txtDairaStd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDairaStdKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 20);
        jPanel4.add(txtDairaStd, gridBagConstraints);

        jLabel78.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel78.setText(" الــعـنــوان ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jLabel78, gridBagConstraints);

        txtAddress_Std.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtAddress_Std.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAddress_Std.setText("...............................................................................................................................................................");
        txtAddress_Std.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAddress_Std.setCaretPosition(100);
        txtAddress_Std.setPreferredSize(new java.awt.Dimension(100, 21));
        txtAddress_Std.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAddress_StdFocusGained(evt);
            }
        });
        txtAddress_Std.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddress_StdKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(txtAddress_Std, gridBagConstraints);

        jLabel79.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel79.setText("الــــجــنـســيـــة  :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 20);
        jPanel4.add(jLabel79, gridBagConstraints);

        jLabel83.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel83.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel83.setText("الحـالـــة  العــائــلـيـة  :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        jPanel4.add(jLabel83, gridBagConstraints);

        National_list.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        National_list.setAutoscrolls(true);
        National_list.setPreferredSize(new java.awt.Dimension(100, 30));
        National_list.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                National_listKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 20);
        jPanel4.add(National_list, gridBagConstraints);

        Sti_Single1.setBackground(new java.awt.Color(255, 255, 255));
        Sti_Single1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Sti_Single1.setSelected(true);
        Sti_Single1.setText("اعـــزب");
        Sti_Single1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Sti_Single1.setBorderPainted(true);
        Sti_Single1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Sti_Single1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sti_Single1ActionPerformed(evt);
            }
        });
        Sti_Single1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Sti_Single1KeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 14, 0, 0);
        jPanel4.add(Sti_Single1, gridBagConstraints);

        Std_Maried.setBackground(new java.awt.Color(255, 255, 255));
        Std_Maried.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Std_Maried.setText("مــتــزوج");
        Std_Maried.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Std_Maried.setBorderPainted(true);
        Std_Maried.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Std_Maried.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Std_MariedActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 38, 0, 0);
        jPanel4.add(Std_Maried, gridBagConstraints);

        CheckMale.setBackground(new java.awt.Color(255, 255, 255));
        CheckMale.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CheckMale.setSelected(true);
        CheckMale.setText("مذكر");
        CheckMale.setToolTipText("");
        CheckMale.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        CheckMale.setBorderPainted(true);
        CheckMale.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CheckMale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CheckMale.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        CheckMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckMaleActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(CheckMale, gridBagConstraints);

        checkFemal.setBackground(new java.awt.Color(255, 255, 255));
        checkFemal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkFemal.setText("مؤنث");
        checkFemal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        checkFemal.setBorderPainted(true);
        checkFemal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        checkFemal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkFemal.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        checkFemal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFemalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(checkFemal, gridBagConstraints);

        PavillonPanInf.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PavillonPanInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PavillonPanInfActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 18, 0, 0);
        jPanel4.add(PavillonPanInf, gridBagConstraints);

        jLabel67.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("الجناح:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 18, 0, 0);
        jPanel4.add(jLabel67, gridBagConstraints);

        jLabel65.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel65.setText("الغرفة");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 25, 0, 0);
        jPanel4.add(jLabel65, gridBagConstraints);

        RomPvinPanInf.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 23, 0, 0);
        jPanel4.add(RomPvinPanInf, gridBagConstraints);

        jCheckBox1.setBackground(new java.awt.Color(204, 204, 204));
        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jCheckBox1.setText("الغاء حجز الغرفة");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jCheckBox1.setBorderPainted(true);
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        jPanel4.add(jCheckBox1, gridBagConstraints);

        ConnectionDB.setText("ConnectionDB");
        ConnectionDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectionDBActionPerformed(evt);
            }
        });
        jPanel4.add(ConnectionDB, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNam_stdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNam_stdFocusGained
        if (txtNam_std.getText().equals(".......................................................................")) {
            txtNam_std.setText("");
        }
        txtNam_std.setForeground(Color.blue);
    }//GEN-LAST:event_txtNam_stdFocusGained

    private void txtNam_stdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNam_stdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtSurNam_std.requestFocus();
        }
    }//GEN-LAST:event_txtNam_stdKeyPressed

    private void DatBirth_stdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DatBirth_stdFocusGained
        DatBirth_std.setForeground(Color.blue);
    }//GEN-LAST:event_DatBirth_stdFocusGained

    private void DatBirth_stdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DatBirth_stdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtPlcBirth_std.requestFocus();
        }
    }//GEN-LAST:event_DatBirth_stdKeyPressed

    private void txtSurNam_stdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSurNam_stdFocusGained
        if (txtSurNam_std.getText().equals("........................................................................")) {
            txtSurNam_std.setText("");
        }
        txtSurNam_std.setForeground(Color.blue);
    }//GEN-LAST:event_txtSurNam_stdFocusGained

    private void txtSurNam_stdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSurNam_stdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DatBirth_std.requestFocus();
        }
    }//GEN-LAST:event_txtSurNam_stdKeyPressed

    private void txtPlcBirth_stdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlcBirth_stdFocusGained
        if (txtPlcBirth_std.getText().equals("................................................................")) {
            txtPlcBirth_std.setText("");
        }
        txtPlcBirth_std.setForeground(Color.blue);
    }//GEN-LAST:event_txtPlcBirth_stdFocusGained

    private void txtPlcBirth_stdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlcBirth_stdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtNam_Father.requestFocus();
        }
    }//GEN-LAST:event_txtPlcBirth_stdKeyPressed

    private void txtNam_FatherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNam_FatherFocusGained
        if (txtNam_Father.getText().equals(".......................................................................")) {
            txtNam_Father.setText("");
        }
        txtNam_Father.setForeground(Color.blue);
    }//GEN-LAST:event_txtNam_FatherFocusGained

    private void txtNam_FatherKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNam_FatherKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtProfission_Std.requestFocus();
        }
    }//GEN-LAST:event_txtNam_FatherKeyPressed

    private void txtProfission_StdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProfission_StdFocusGained
        if (txtProfission_Std.getText().equals("........................................................................")) {
            txtProfission_Std.setText("");
        }
        txtProfission_Std.setForeground(Color.blue);
    }//GEN-LAST:event_txtProfission_StdFocusGained

    private void txtProfission_StdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfission_StdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfission_StdActionPerformed

    private void txtProfission_StdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProfission_StdKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtNam_mother.requestFocus();
        }
    }//GEN-LAST:event_txtProfission_StdKeyPressed

    private void txtNam_motherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNam_motherFocusGained
        if (txtNam_mother.getText().equals("..................................................................")) {
            txtNam_mother.setText("");
        }
        txtNam_mother.setForeground(Color.blue);
    }//GEN-LAST:event_txtNam_motherFocusGained

    private void txtNam_motherKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNam_motherKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            LastNamMothARTxt.requestFocus();
            //txtProfission_Moth.requestFocus();
        }
    }//GEN-LAST:event_txtNam_motherKeyPressed

    private void LastNamMothARTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LastNamMothARTxtFocusGained
        if (LastNamMothARTxt.getText().equals("..............................")) {
            LastNamMothARTxt.setText("");
        }
        LastNamMothARTxt.setForeground(Color.blue);
    }//GEN-LAST:event_LastNamMothARTxtFocusGained

    private void LastNamMothARTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNamMothARTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNamMothARTxtActionPerformed

    private void LastNamMothARTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LastNamMothARTxtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            txtProfission_Moth.requestFocus();
        }
    }//GEN-LAST:event_LastNamMothARTxtKeyPressed

    private void txtProfission_MothFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProfission_MothFocusGained
        if (txtProfission_Moth.getText().equals(".......................................................................")) {
            txtProfission_Moth.setText("");
        }
        txtProfission_Moth.setForeground(Color.blue);
    }//GEN-LAST:event_txtProfission_MothFocusGained

    private void txtProfission_MothKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProfission_MothKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtAddress_Std.requestFocus();
        }
    }//GEN-LAST:event_txtProfission_MothKeyPressed

    private void WilayaListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WilayaListActionPerformed
        //F.FillTableCommune_Combobox((String) WilayaList.getSelectedItem(), null, ComboxHome, 1);
    }//GEN-LAST:event_WilayaListActionPerformed

    private void WilayaListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WilayaListKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtDairaStd.requestFocus();
        }
    }//GEN-LAST:event_WilayaListKeyPressed

    private void ComboxHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboxHomeActionPerformed
        //        String CommuneSlc=(String)ComboxHome.getSelectedItem();
        //        if (!CommuneSlc.equals("اختر البلدية")) {
            //            CommuneSlc.setText(CommuneSlc);
            //        }
    }//GEN-LAST:event_ComboxHomeActionPerformed

    private void txtDairaStdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDairaStdFocusGained
        if (txtDairaStd.getText().equals("........................................")) {
            txtDairaStd.setText("");
        }
        txtDairaStd.setForeground(Color.blue);
    }//GEN-LAST:event_txtDairaStdFocusGained

    private void txtDairaStdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDairaStdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ComboxHome.requestFocus();
        }
    }//GEN-LAST:event_txtDairaStdKeyPressed

    private void txtAddress_StdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddress_StdFocusGained
        if (txtAddress_Std.getText().equals("...............................................................................................................................................................")) {
            txtAddress_Std.setText("");
        }
        txtAddress_Std.setForeground(Color.blue);
    }//GEN-LAST:event_txtAddress_StdFocusGained

    private void txtAddress_StdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddress_StdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            WilayaList.requestFocus();
        }
    }//GEN-LAST:event_txtAddress_StdKeyPressed

    private void National_listKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_National_listKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            CheckMale.requestFocus();
        }
    }//GEN-LAST:event_National_listKeyPressed

    private void Sti_Single1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sti_Single1ActionPerformed
        if (Sti_Single1.isSelected()) {
            Std_Maried.setSelected(false);
            SituationFam = Sti_Single1.getText();
           
        } else {
            Std_Maried.setSelected(true);
            SituationFam = Std_Maried.getText();

        }
    }//GEN-LAST:event_Sti_Single1ActionPerformed

    private void Sti_Single1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Sti_Single1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sti_Single1KeyPressed
    String SituationFam;
    private void Std_MariedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Std_MariedActionPerformed
        if (Std_Maried.isSelected()) {
            Sti_Single1.setSelected(false);
            SituationFam = Std_Maried.getText();
           
        } else {
            Sti_Single1.setSelected(true);
            SituationFam = Sti_Single1.getText();
            
        }
    }//GEN-LAST:event_Std_MariedActionPerformed
    int Gender;
    private void CheckMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckMaleActionPerformed
        if (CheckMale.isSelected()) {
            checkFemal.setSelected(false);
            Gender = 1;
            Sti_Single1.requestFocus();
        } else {
            checkFemal.setSelected(true);
            Sti_Single1.requestFocus();
            Gender = 2;
        }
    }//GEN-LAST:event_CheckMaleActionPerformed

    private void checkFemalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFemalActionPerformed
        if (checkFemal.isSelected()) {
            CheckMale.setSelected(false);
            Gender = 2;
            Sti_Single1.requestFocus();
        } else {
            CheckMale.setSelected(true);
            Gender = 1;
        }
    }//GEN-LAST:event_checkFemalActionPerformed

    private void PavillonPanInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PavillonPanInfActionPerformed
       // RoomRemplissage.FillComboboxRooms(RomPvinPanInf, (String) PavillonPanInf.getSelectedItem());
    }//GEN-LAST:event_PavillonPanInfActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            PavillonPanInf.setEnabled(false);
            RomPvinPanInf.setEnabled(false);
        } else {
            PavillonPanInf.setEnabled(true);
            RomPvinPanInf.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void ConnectionDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectionDBActionPerformed
        FormTestFreeDesignLayout.ConnectingAccess();
    }//GEN-LAST:event_ConnectionDBActionPerformed

    private static void ConnectingAccess(){
        try {
Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String DB;
            System.out.println("Success Download ");          
            DB = "jdbc:ucanaccess:////D:\\Base.accdb";
            
            DB = "jdbc:ucanaccess:////D:\\att2000.mdb";
             Connection cnnct=DriverManager.getConnection(DB);
                System.out.println("Success Connecting... ");
           // JOptionPane.showMessageDialog(null, "The connection is etablished...");
        } catch (SQLException e) {
           JOptionPane.showMessageDialog(null, "Eroooooor conect for Server  "+e.getMessage());
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ConnectionDB.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTestFreeDesignLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTestFreeDesignLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTestFreeDesignLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTestFreeDesignLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
    
        
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormTestFreeDesignLayout().setVisible(true);
//            }
//        });
    
        FormTestFreeDesignLayout.ConnectingAccess();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckMale;
    private javax.swing.JComboBox<String> ComboxHome;
    private javax.swing.JButton ConnectionDB;
    private javax.swing.JFormattedTextField DatBirth_std;
    private javax.swing.JTextField LastNamMothARTxt;
    private javax.swing.JComboBox<String> National_list;
    private javax.swing.JComboBox<String> PavillonPanInf;
    private javax.swing.JComboBox<String> RomPvinPanInf;
    private javax.swing.JCheckBox Std_Maried;
    private javax.swing.JCheckBox Sti_Single1;
    private javax.swing.JComboBox<String> WilayaList;
    private javax.swing.JCheckBox checkFemal;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtAddress_Std;
    private javax.swing.JTextField txtDairaStd;
    private javax.swing.JTextField txtNam_Father;
    private javax.swing.JTextField txtNam_mother;
    private javax.swing.JTextField txtNam_std;
    private javax.swing.JTextField txtPlcBirth_std;
    private javax.swing.JTextField txtProfission_Moth;
    private javax.swing.JTextField txtProfission_Std;
    private javax.swing.JTextField txtSurNam_std;
    // End of variables declaration//GEN-END:variables
}
